XArapucas Updates
SBNSoftware/sbndcode pull request #133
Opened 2021-08-04 11:01 UTC by rodralva

XArapuca Updates in the OpDetSim Module related to issues [#78](https://github.com/SBNSoftware/sbndcode/issues/78), [#80](https://github.com/SBNSoftware/sbndcode/issues/80) :

-Added new sampling field to the sbnd_pds_mapping.json file.
-Modified digitizer, op hit finder, wvf analyzer and trigger modules to differentiate daphne xarapuca channels with their own frequency. 
-Updated test bench XArapuca single electron response.

I'm currently loading the data driven response [from](https://github.com/SBNSoftware/sbndcode/blob/feature/rodrigoa_XArapucasUpdates/sbndcode/OpDetSim/DigiArapucaSBNDAlg.cc#L59) /sbnd/app/users/rodrigoa/digi_arapuca_sbnd.root, this should be changed to the usual file in sbnd_data repo ([OpDetSim/digi_arapuca_sbnd.root](https://github.com/SBNSoftware/sbndcode/blob/feature/rodrigoa_XArapucasUpdates/sbndcode/OpDetSim/digi_arapuca_sbnd.fcl#L27)), as soon as the file is updated adding the vector with the response data.

2021-08-04 11:47 UTC, ikatza commented
I'm happy to take this one since I opened the issues.

2021-08-04 13:11 UTC, ikatza commented
I believe this could use some refactoring. I've agreed to have a call with @rodralva to work on this, instead of writing all of my observations in here.

2021-08-05 21:40 UTC, wesketchum commented
Assigned to upcoming production milestone, but I think if it needs more time it's ok to go. Also, further refactoring work can be done later if we think the code is OK now and it is important to start testing.

2021-08-09 10:03 UTC, rodralva commented
I ran some test on the same G4 Event and printed the digitized waveforms with different configurations, everything looks fine. ![image](https://user-images.githubusercontent.com/70945401/128690004-58531174-9f62-4bc2-ae00-fd3a62f3a55d.png)

2021-08-09 11:16 UTC, pgreen135 commented
@rodralva is this PR now ready (pending CI test results)? if so @ikatza can you confirm that your concerns have been addressed / repeat the review?

2021-08-09 11:40 UTC, rodralva commented
Yes, it is. For the CI test: I switched the [ideal response to default](https://github.com/SBNSoftware/sbndcode/blob/feature/rodrigoa_XArapucasUpdates/sbndcode/OpDetSim/digi_arapuca_sbnd.fcl#L28) (to use the test response, change the SinglePEmodel parameter to true). Also, keep in mind that the test response is loaded from sbnd_data 01_08_00 version.

2021-08-09 12:46 UTC, ikatza commented on sbndcode/OpDetSim/sbndPDMapAlg_tool.cc
> +    if(PDmap.at(ch)["electronics"] == std::string(pdname)) return true; // TODO: add number of electronics, daphne01, daphne02, .... ~rodrigoa; at() throws an exception if no such channel
fine to leave the TODO, but the comment about `at()` is not necessary

2021-08-09 12:48 UTC, ikatza commented on sbndcode/OpDetSim/sbndPDMapAlg_tool.cc
> +    if(ch < PDmap.size()) return PDmap.at(ch)["pd_type"];//TODO: remove all if(ch < PDmap.size()) ~rodrigoa
the `if(ch < PDmap.size())` is not necessary

2021-08-09 12:49 UTC, ikatza commented on sbndcode/OpDetSim/sbndPDMapAlg_tool.cc
>      return "There is no such channel";
Can you remove this return please, if it fails to find the channel is better to throw an exception from `at()`

2021-08-09 12:51 UTC, ikatza commented on sbndcode/OpDetSim/wvfAna_module.cc
> +    fSampling_Daphne=p.get<double >("DaphneFrequency" );
Please, spaces around `=`, and remove the leading spaces between `>` and `)`

2021-08-09 12:52 UTC, ikatza commented on sbndcode/OpDetSim/wvfAna_module.cc
> +			else{
maybe is just GitHub rendering but indentation here seems wrong

2021-08-09 12:52 UTC, ikatza commented on sbndcode/OpDetSim/wvfAna_module.cc
> +      fEndTime = double(wvf.size()) / fSampling + fStartTime;} //in us
curly brace on new line

2021-08-09 12:52 UTC, ikatza commented on sbndcode/OpDetSim/wvfana.fcl
>                   "arapuca_vuv", "arapuca_vis"]
kill `"arapuca_vuv", "arapuca_vis"` please

2021-08-09 12:55 UTC, ikatza commented on sbndcode/OpDetSim/opDetDigitizerWorker.cc
> +			    if(is_daphne){
indentation

2021-08-09 12:55 UTC, ikatza commented on sbndcode/OpDetSim/opDetDigitizerWorker.cc
> +            }else{
new line for `else`

2021-08-09 12:56 UTC, ikatza commented on sbndcode/OpDetSim/opDetDigitizerWorker.cc
> +        }else{
idem

2021-08-09 12:57 UTC, ikatza commented on sbndcode/OpDetSim/opDetDigitizerWorker.cc
> +											  }
indentation?

2021-08-09 12:57 UTC, ikatza commented on sbndcode/OpDetSim/ophitfinder_sbnd.fcl
> +  DaphneFrequency: 					80.0  #in MHz. Frequency of the Daphne Readouts
align the value with others please

2021-08-09 12:58 UTC, ikatza commented on sbndcode/OpDetSim/opHitFinderSBND_module.cc
> +    void subtractBaseline(std::vector<double>& waveform, std::string pdtype, std::string electronicsType,double& rms);
missing a space

2021-08-09 12:59 UTC, ikatza commented on sbndcode/OpDetSim/opHitFinderSBND_module.cc
> +    fSampling_Daphne = p.get<double >("DaphneFrequency" );;
extra spaces, extra `;`

2021-08-09 12:59 UTC, ikatza commented on sbndcode/OpDetSim/opHitFinderSBND_module.cc
> +      subtractBaseline(fwaveform, opdetType,electronicsType, rms);
missing space

2021-08-09 13:00 UTC, ikatza commented on sbndcode/OpDetSim/opHitFinderSBND_module.cc
> +      while(findAndSuppressPeak(fwaveform, timebin, Area, amplitude, threshold, opdetType,electronicsType)){
missing space

2021-08-09 13:02 UTC, ikatza commented on sbndcode/OpDetSim/opHitFinderSBND_module.cc
> +        time = wvf.TimeStamp() + (double)timebin / fSampling;}
better do:

```
if(electronicsType == "Daphne") time = wvf.TimeStamp() + (double)timebin / fSampling_Daphne;
else time = wvf.TimeStamp() + (double)timebin / fSampling;
```

or fix the indentation and add new lines for the curlies

2021-08-09 13:02 UTC, ikatza commented on sbndcode/OpDetSim/opHitFinderSBND_module.cc
> +                                         std::string pdtype,std::string electronicsType, double& rms)
missing space

2021-08-09 13:07 UTC, ikatza commented on sbndcode/OpDetSim/DigiArapucaSBNDAlg.hh
>        CLHEP::HepRandomEngine* engine = nullptr;
I thought we agreed these could be `const`

2021-08-09 13:10 UTC, ikatza commented on sbndcode/OpDetSim/DigiArapucaSBNDAlg.hh
>        CLHEP::HepRandomEngine* engine = nullptr;
where is `engine` used? below there's an `fEngine`

2021-08-09 13:11 UTC, ikatza commented on sbndcode/OpDetSim/DigiArapucaSBNDAlg.hh
>        CLHEP::HepRandomEngine* engine = nullptr;
also above, please kill `ArapucaVUVEff` and `ArapucaVISEff`

2021-08-09 13:13 UTC, ikatza commented on sbndcode/OpDetSim/DigiArapucaSBNDAlg.hh
> +    CLHEP::HepRandomEngine* fEngine; //!< Reference to art-managed random-number engine //check this works ~rodrigoa
what needs to be checked? is it to do with the `const`?

perhaps a comment that can be removed?

2021-08-09 13:15 UTC, ikatza commented on sbndcode/OpDetSim/DigiArapucaSBNDAlg.cc
> +		  }
indentation

2021-08-09 13:17 UTC, ikatza commented on sbndcode/OpDetSim/DigiArapucaSBNDAlg.cc
> +          if(timeBin < wave.size()) {
maybe a GitHub rendering, but the lines don't seem aligned

2021-08-09 13:17 UTC, ikatza commented on sbndcode/OpDetSim/DigiArapucaSBNDAlg.cc
> +          }
idem, alignment

2021-08-09 13:18 UTC, ikatza commented on sbndcode/OpDetSim/DigiArapucaSBNDAlg.cc
> +		}
indentation

2021-08-09 13:19 UTC, ikatza commented on sbndcode/OpDetSim/DigiArapucaSBNDAlg.cc
> +		fBaseConfig.frequency_Daphne= config.DaphneFrequency();
indentation

2021-08-09 13:20 UTC, ikatza requested changes
Missing is mostly indentation and styling issues.

2021-08-09 14:56 UTC, rodralva commented on sbndcode/OpDetSim/sbndPDMapAlg_tool.cc
> +    if(PDmap.at(ch)["electronics"] == std::string(pdname)) return true; // TODO: add number of electronics, daphne01, daphne02, .... ~rodrigoa; at() throws an exception if no such channel
Removed the second comment

2021-08-09 14:57 UTC, rodralva commented on sbndcode/OpDetSim/sbndPDMapAlg_tool.cc
> +    if(ch < PDmap.size()) return PDmap.at(ch)["pd_type"];//TODO: remove all if(ch < PDmap.size()) ~rodrigoa
Removed the if

2021-08-09 14:58 UTC, rodralva commented on sbndcode/OpDetSim/wvfAna_module.cc
> +			else{
I believe is GitHub rendering 
![image](https://user-images.githubusercontent.com/70945401/128727654-218d5e34-73ad-47dc-ab6c-245fd7968f9b.png)

2021-08-09 15:01 UTC, rodralva commented on sbndcode/OpDetSim/wvfAna_module.cc
> +      fEndTime = double(wvf.size()) / fSampling + fStartTime;} //in us
Fixed
![image](https://user-images.githubusercontent.com/70945401/128728055-a903a90c-4f6a-4fd3-8f28-90e8d6a7a26f.png)

2021-08-09 15:04 UTC, rodralva commented on sbndcode/OpDetSim/opDetDigitizerWorker.cc
> +			    if(is_daphne){
Again, I believe is github messing up tabs and spaces 
![image](https://user-images.githubusercontent.com/70945401/128728485-b39b86bf-6a77-4b38-9d93-4f728b42b936.png)

2021-08-09 15:24 UTC, ikatza commented on sbndcode/OpDetSim/opDetDigitizerWorker.cc
> +			    if(is_daphne){
So in that picture `arapucaDigitizer`  should start two spaces to the right. `litesimephotons, waveform, ...` should start even further to the right.

But whatevs, honestly future work is required in this module.

2021-08-09 15:27 UTC, rodralva commented on sbndcode/OpDetSim/DigiArapucaSBNDAlg.hh
>        CLHEP::HepRandomEngine* engine = nullptr;
We made const the ones labeled with and f before them: 
![image](https://user-images.githubusercontent.com/70945401/128731574-9a366c51-cfa7-4b40-9e33-342b188c9761.png)

2021-08-09 15:40 UTC, rodralva commented on sbndcode/OpDetSim/DigiArapucaSBNDAlg.hh
>        CLHEP::HepRandomEngine* engine = nullptr;
It is the engine that initializes the fEngine in the .cc file:
![image](https://user-images.githubusercontent.com/70945401/128732738-088ac9f1-8ae4-4f7f-9531-1a1d2e2beef2.png)

2021-08-09 15:46 UTC, rodralva commented on sbndcode/OpDetSim/DigiArapucaSBNDAlg.hh
> +    CLHEP::HepRandomEngine* fEngine; //!< Reference to art-managed random-number engine //check this works ~rodrigoa
Yes, seems like fEngine cant be made const:
![image](https://user-images.githubusercontent.com/70945401/128734637-8cf96ff3-1502-4c23-a058-7bbb151cc075.png)

2021-08-09 16:01 UTC, rodralva commented on sbndcode/OpDetSim/DigiArapucaSBNDAlg.cc
> +          if(timeBin < wave.size()) {
I believe they are 
![image](https://user-images.githubusercontent.com/70945401/128737202-b590366f-05de-45ec-8687-3b4f2bc71653.png)

2021-08-09 16:19 UTC, pgreen135 commented
trigger build

2021-08-09 16:20 UTC, FNALbuild commented
CI build for LArSoft on slf7 for c7:prof is in progress -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/12138&builds=)

2021-08-09 16:20 UTC, FNALbuild commented
CI build for LArSoft on slf7 for e20:prof is in progress -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/12139&builds=)

2021-08-09 16:20 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c7:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/12138&builds=)

2021-08-09 16:20 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for e20:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/12139&builds=)

2021-08-09 16:21 UTC, FNALbuild commented
CI build for SBND on slf7 for c7:prof is in progress -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/6955&builds=)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/12138&builds=)

2021-08-09 16:21 UTC, FNALbuild commented
CI build for SBND on slf7 for e20:prof is in progress -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/6956&builds=)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/12139&builds=)

2021-08-09 16:35 UTC, ikatza approved these changes
Thanks a lot for changing these @rodralva

2021-08-09 16:38 UTC, FNALbuild commented
:warning: CI build for SBND Warning at phase ci_tests SBND on slf7 for c7:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/6955&builds=)

:rotating_light: For more details about the warning phase, check the [ci_tests SBND phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/6955&platform=Linux%203.10.0-1160.31.1.el7.x86_64&phase=ci_tests&buildtype=slf7%20c7:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/12138&builds=)

2021-08-09 16:39 UTC, FNALbuild commented
:warning: CI build for SBND Warning at phase ci_tests SBND on slf7 for e20:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/6956&builds=)

:rotating_light: For more details about the warning phase, check the [ci_tests SBND phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/6956&platform=Linux%203.10.0-1160.31.1.el7.x86_64&phase=ci_tests&buildtype=slf7%20e20:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/12139&builds=)

2021-08-09 17:49 UTC, ikatza commented
There should have been a warning from the reco stage, stating that there are less `OpHits`.

2021-08-09 20:32 UTC, pgreen135 commented
@rodralva @ikatza are the changes in the e20:prof CI tests above as expected? I am seeing small changes in the number of std::vector<raw::OpDetWaveform>, which seems to make sense.

@ikatza the reco stages use the reference detsim files as input, so wouldn't be affected by these changes in the detsim stage

2021-08-10 08:14 UTC, ikatza commented
@rodralva should comment on this as he's the expert.

In this case I feel like this highlights a case were the CI as it is rather insensitive. Instead of the number of waveform we would like to know the size of these. Or as I was expecting how these changes affect further down the line.

2021-08-10 08:30 UTC, rodralva commented
The number of waveforms remains the same. What I have seen is that the size of the output waveforms decreases notably. For example, running the wvf analizer to dump the digitizer waveforms on single interaction muon events produces 1.8 mb output files per event with develop. This goes down to 1.2/1.3 mb with this PR(~30% reduction). As for the reco stage, we are losing resolution, as the time tick goes from 2ns to 12.5 ns, but the fall time of the Xarapucas is greater than 100ns so the difference should be small. The test still used the ideal response, no big differences are expected(the waveforms have wider binning, but the shape remains the same) .

2021-08-10 08:50 UTC, pgreen135 commented
@rodralva does that mean these changes in the CI tests are not expected then? e.g. in the singles test:

`397: < DetSim | opdaq |  | std::vector<raw::OpDetWaveform> | 253
398: ---
399: > DetSim | opdaq |  | std::vector<raw::OpDetWaveform> | 245`

If so, could you investigate further, thanks.

2021-08-10 12:54 UTC, merged