Adding module for light signals deconvolution
SBNSoftware/sbndcode pull request #144
Opened 2021-08-11 17:18 UTC by fjnicolas

This PR adds a new module that performs signals deconvolution for the PMTs:

- New module added in sbndcode/OpDetReco/OpDeconvolution
- EDProducer module in OpDeconvolution/SBNDOpDeconvolution_module.cc
- Deconvolution library implemented OpDeconvolution/Alg
- Running fhicls in OpDeconvolution/reco_deco_sbnd

More details about the implementation in https://sbn-docdb.fnal.gov/cgi-bin/sso/ShowDocument?docid=22863 (docdb 22863).

2021-08-17 19:53 UTC, wesketchum requested changes
Highly suggest making the OpDeconvolutionAlg an art tool:
https://cdcvs.fnal.gov/redmine/projects/art/wiki/Guide_to_writing_and_using_tools

I think it should be able to be done relatively easily, and will provide a better/more framework based interface to what I think you are trying to do (and may allow for different kinds of deconvolution algs in the future).

2021-08-17 19:53 UTC, wesketchum commented on sbndcode/OpDetReco/OpDeconvolution/SBNDOpDeconvolution_module.cc
> +  fOpDecoAlg = new opdet::OpDeconvolutionAlg(opdeco_pset);
Not sure why fOpDecoAlg needs to be a pointer? But if it does, think it'd be better to make it a unique_pointer or something like that?

2021-08-17 19:53 UTC, wesketchum commented on sbndcode/OpDetReco/OpDeconvolution/SBNDOpDeconvolution_module.cc
> +   std::cout<<"Non valid waveform handle\n";
cout statement ok, but think you should throw an error if it has bad input (maybe art will do this already since you declared produces? but would suggest guaranteeing it throws an error with a useful message)

2021-08-17 19:53 UTC, wesketchum commented on sbndcode/OpDetReco/OpDeconvolution/Alg/OpDeconvolutionAlg.hh
> +  std::vector<raw::OpDetWaveform> RunDeconvolution(std::vector<raw::OpDetWaveform> wfHandle);
pass input in by reference

2021-08-17 19:53 UTC, wesketchum commented on sbndcode/OpDetReco/OpDeconvolution/Alg/OpDeconvolutionAlg.hh
> +std::vector<double> opdet::OpDeconvolutionAlg::CreateNoiseHypothesis(size_t n, double baseline_stddev){
not used?

2021-08-17 19:53 UTC, wesketchum commented on sbndcode/OpDetReco/OpDeconvolution/Alg/OpDeconvolutionAlg.hh
> +double opdet::OpDeconvolutionAlg::EstimateBaseline(std::vector<double> &wf){
not used?

2021-08-17 19:53 UTC, wesketchum commented on sbndcode/OpDetReco/OpDeconvolution/SBNDOpDeconvolution_module.cc
> +  DecoWfVector=fOpDecoAlg->RunDeconvolution(DecoWfVector);
Is it necessary to overwrite your input waveform vector with the output? I would think something like:

```
std::unique_ptr< std::vector< raw::OpDetWaveform > > DecoWf_VecPtr(std::make_unique< std::vector< raw::OpDetWaveform > > ());
auto const& DecoWf_Vec(*DecoWf_VecPtr);
DecoWf_Vec = fOpDecoAlg->RunDeconvolution(*wfHandle);
```
should work? Or something like that?

2021-08-18 13:57 UTC, wesketchum commented on sbndcode/OpDetReco/OpDeconvolution/SBNDOpDeconvolution_module.cc
> +   std::cout<<"Non valid waveform handle\n";
Ah, sorry, I meant throw an exception too. Like: 

```
throw cet::exception("SBNDOpDeconvolution") << "Input waveforms with input label " << fInputLabel << " not found";
```

2021-08-18 13:59 UTC, wesketchum commented on sbndcode/OpDetReco/OpDeconvolution/SBNDOpDeconvolution_module.cc
>      if(std::find(fPDTypes.begin(), fPDTypes.end(), pdsmap.pdType(wf.ChannelNumber()) ) != fPDTypes.end() ){
Is there a reason you need to extract only certain waveforms? PMT vs. SiPM types? It'd be nice to avoid this, but maybe then this is a demand on the input data collections (e.g. different instances...)

2021-08-18 14:20 UTC, fjnicolas commented on sbndcode/OpDetReco/OpDeconvolution/SBNDOpDeconvolution_module.cc
>      if(std::find(fPDTypes.begin(), fPDTypes.end(), pdsmap.pdType(wf.ChannelNumber()) ) != fPDTypes.end() ){
Yes the input std::vector<raw::OpDetWaveform> contains both the PMTs and the SiPMs so we need to select what waveforms we want to deconvolve (SiPMs and PMTs responses are very different so configuration parameters used for PMT deconvolution won't work for the SiPMs).

2021-08-19 12:35 UTC, fjnicolas commented
Added art tool with commit de87870

2021-08-20 17:14 UTC, mstancar approved these changes

2021-08-23 09:46 UTC, pgreen135 commented
trigger build

2021-08-23 09:47 UTC, FNALbuild commented
CI build for LArSoft on slf7 for c7:prof is in progress -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/12308&builds=)

2021-08-23 09:47 UTC, FNALbuild commented
CI build for LArSoft on slf7 for e20:prof is in progress -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/12307&builds=)

2021-08-23 09:48 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c7:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/12308&builds=)

2021-08-23 09:48 UTC, FNALbuild commented
CI build for SBND on slf7 for c7:prof is in progress -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/7052&builds=)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/12308&builds=)

2021-08-23 10:09 UTC, FNALbuild commented
:warning: CI build for SBND Warning at phase ci_tests SBND on slf7 for c7:prof - ignored warnings for build -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/7052&builds=)

:rotating_light: For more details about the warning phase, check the [ci_tests SBND phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/7052&platform=Linux%203.10.0-1160.31.1.el7.x86_64&phase=ci_tests&buildtype=slf7%20c7:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/12308&builds=)

2021-08-23 10:18 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for e20:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/12307&builds=)

2021-08-23 10:18 UTC, FNALbuild commented
CI build for SBND on slf7 for e20:prof is in progress -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/7056&builds=)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/12307&builds=)

2021-08-23 10:46 UTC, FNALbuild commented
:warning: CI build for SBND Warning at phase ci_tests SBND on slf7 for e20:prof - ignored warnings for build -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/7056&builds=)

:rotating_light: For more details about the warning phase, check the [ci_tests SBND phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/7056&platform=Linux%203.10.0-1160.31.1.el7.x86_64&phase=ci_tests&buildtype=slf7%20e20:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/12307&builds=)

2021-08-23 10:55 UTC, pgreen135 commented
@wesketchum do the changes @fjnicolas has made address the issues/comments from your review? if so, I am happy for this to be included in the next release

2021-08-23 10:56 UTC, pgreen135 approved these changes

2021-08-24 12:46 UTC, wesketchum approved these changes

2021-08-24 12:47 UTC, wesketchum commented
Looks good!

2021-08-24 13:49 UTC, merged