Feature/lynnt comm
SBNSoftware/sbndcode pull request #179
Opened 2021-09-10 22:30 UTC by lynnt-uchicago

pull request for the crossing muon modules for comissioning. I also have a readme included for my feature branch, but not sure if there's a way to exclude it from the pull request?

2021-09-11 13:29 UTC, mstancar approved these changes
Looks good

2021-09-13 14:27 UTC, marcodeltutto requested changes
Thank you @lynnt-uchicago! Looks great! I added a few minor comments if you don't mind taking a look at them. As per the README file, I'd suggest you move it to the `sbndcode/Commissioning` directory instead of removing it, it's nice to have documentation written down!

2021-09-13 14:27 UTC, marcodeltutto commented on sbndcode/Commissioning/MuonTrackProducer_module.cc
> +#define PI 3.14159265
I'd suggest we don't re-define `PI`. You can remove this line and use `M_PI` in your code.

2021-09-13 14:27 UTC, marcodeltutto commented on sbndcode/Commissioning/MuonTrackProducer_module.cc
> +   std::vector<int> fKeepMuonTypes = {0, 1, 2, 3, 4, 5};
Can you please add a comment next to these variables? This will make it easier for people to understand what they and how they are used later. Also describing the muon types, or referring to another part of the code where they are defined.

2021-09-13 14:27 UTC, marcodeltutto commented on sbndcode/Commissioning/MuonTrackProducer_module.cc
> +   ResetCollectionHitVectors(20);
Do we want this `20` to be hardcoded, or also configurable via a fcl parameter? (also later in the code)

2021-09-13 14:27 UTC, marcodeltutto commented on sbndcode/Commissioning/MuonTrackProducer_module.cc
> +   for (int i=0; i<int(outlines.size()); i++){
I'd suggest we don't use C-casting (with `int()`). In this case, you can  use `size_t`: `for (size_t  i = 0; i < outlines.size(); i++) {`

2021-09-13 14:27 UTC, marcodeltutto commented on sbndcode/Commissioning/MuonTrackProducer_module.cc
> +   hit_02.reserve(3000);
Just wanted to make sure that having these numbers hardcoded is intentional? Also in `ResetInductionHitVectors`

2021-09-13 14:27 UTC, marcodeltutto commented on README.md
> +# Crossing muon tracks
Having this README file would be nice, why don't you move it to the `sbndcode/Commissioning` directory?

2021-09-13 14:28 UTC, marcodeltutto commented
@pgreen135 Just a heads up that this PR depends on SBNSoftware/sbnobj#26

2021-09-13 14:40 UTC, pgreen135 commented
thanks @marcodeltutto, I'll make sure these go in together

2021-09-13 23:05 UTC, lynnt-uchicago commented on sbndcode/Commissioning/MuonTrackProducer_module.cc
> +   hit_02.reserve(3000);
Question about these actually: these hard coded numbers are an estimate of how many induction/collection hits there are in a given event. I could easily move them to a fcl parameter (like I did with another hardcoded number), but unsure if that's actually more helpful in the long run?

2021-09-13 23:06 UTC, lynnt-uchicago commented
realized that I need to add the muonhit info from the association in the producer, will be working on that!

2021-09-14 13:05 UTC, cjbackhouse commented on sbndcode/Commissioning/MuonTrackProducer_module.cc
> +   hit_02.reserve(3000);
Butting in: I don't think anyone is going to be interested in configuring `reserve()` calls from fcl. It's solely a performance optimization, which probably has negligible effect here. I would just leave them, or potentially remove the `reserve()` calls since I doubt they really matter.

2021-09-14 15:08 UTC, marcodeltutto commented on sbndcode/Commissioning/MuonTrackProducer_module.cc
> +   hit_02.reserve(3000);
Yes, no need to make this fhicl configurable. I think there is some benefit in having these `reserve` as the vectors are filled with `push_back` so having the memory reserved beforehand will save some time. I would just leave them there too as they are. Thanks!

2021-09-16 14:20 UTC, marcodeltutto approved these changes
Looks good! Thank you! Please just remove the three lines in the `.gitignore` file, otherwise this is good to go!

2021-09-16 14:20 UTC, marcodeltutto commented on .gitignore
> +sbndcode/Commissioning/safe/run_acproducer.fcl
I think these lines are for you setup @lynnt-uchicago, can we remove them from this PR so they don't end up in our common repo? Thanks!

2021-09-16 14:24 UTC, pgreen135 commented
trigger build SBNSoftware/sbnobj#26

2021-09-16 14:24 UTC, FNALbuild commented
CI build for LArSoft on slf7 for e20:prof is in progress -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/12563&builds=)

2021-09-16 14:24 UTC, FNALbuild commented
CI build for LArSoft on slf7 for c7:prof is in progress -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/12562&builds=)

2021-09-16 14:26 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for e20:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/12563&builds=)

2021-09-16 14:26 UTC, FNALbuild commented
CI build for SBND on slf7 for c7:prof is in progress -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/7181&builds=)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/12562&builds=)

2021-09-16 14:26 UTC, FNALbuild commented
CI build for SBND on slf7 for e20:prof is in progress -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/7182&builds=)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/12563&builds=)

2021-09-16 14:48 UTC, FNALbuild commented
:warning: CI build for SBND Warning at phase ci_tests SBND on slf7 for c7:prof - ignored warnings for build -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/7181&builds=)

:rotating_light: For more details about the warning phase, check the [ci_tests SBND phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/7181&platform=Linux%203.10.0-1160.31.1.el7.x86_64&phase=ci_tests&buildtype=slf7%20c7:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/12562&builds=)

2021-09-16 14:50 UTC, FNALbuild commented
:warning: CI build for SBND Succeeded with warning at phase build on slf7 for e20:prof - ignored warnings for build -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/7182&builds=)


parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/12563&builds=)

2021-09-21 09:13 UTC, merged