Feature/fnicolas sprfluc
SBNSoftware/sbndcode pull request #180
Opened 2021-09-14 12:48 UTC by fjnicolas

This PR adds an art tool to simulate PMT gain fluctuations (algorithm taken from icaruscode/PMT/Algorithms/PMTsimulationAlg.h). More details can be found in [docdb-23286](https://sbn-docdb.fnal.gov/cgi-bin/sso/ShowDocument?docid=23286). Code modifications:
- Added [PMTAlg](https://github.com/SBNSoftware/sbndcode/tree/feature/fnicolas_sprfluc/sbndcode/OpDetSim/PMTAlg) directory containing the art tool for gain fluctuations
- Added modified version for the 'AddSPE' function in [DigiPMTSBNDAlg.cc](https://github.com/SBNSoftware/sbndcode/blob/feature/fnicolas_sprfluc/sbndcode/OpDetSim/DigiArapucaSBNDAlg.cc#L261)

Note that the MakeGainFluctuations parameter in [digi_pmt_sbnd.root](https://github.com/SBNSoftware/sbndcode/blob/feature/fnicolas_sprfluc/sbndcode/OpDetSim/digi_pmt_sbnd.fcl#L36) is set to true, so **SER fluctuation are simulated by default with this PR**.

2021-09-14 19:53 UTC, ikatza commented on sbndcode/OpDetSim/PMTAlg/PMTGainFluctuations1Dynode_tool.cc
> +  unsigned int fGain;
I believe this variable should be a double. Certainly that's the type of the input on the fcl file.

2021-09-14 19:55 UTC, ikatza commented on sbndcode/OpDetSim/PMTAlg/pmtgainfluctuations_config.fcl
> +  VoltageDistribution:    [ 17.4, 3.4, 5.0, 3.33, 1.67, 1.0, 1.2, 1.5, 2.2, 3.0 ]
Where do these values come from? If they're provisional, but say have to be calibrated, it would be good to add a TODO somewhere.

2021-09-14 19:58 UTC, ikatza requested changes
All looks good and sensible. Please only comment on the `int/double` variable.

2021-09-15 01:42 UTC, PetrilloAtWork reviewed
The code looks correct to me.
I have left two recommendations and one suggestion, plus a few comments.
As such, none of them is a show stopper for merging but I invite you to consider them carefully.

I was under the impression that SBND was using `sim::SimPhotonsLite`, but I only see photons added one by one. I am surprised... but I did not see the full code, only the highlights from GitHub, so I have missed a lot.

2021-09-15 01:42 UTC, PetrilloAtWork commented on sbndcode/OpDetSim/DigiPMTSBNDAlg.cc
> +        }
These two (or four) lines are very popular:
```suggestion
        AddSPEwithFluctuations(wave, timeBin);
```
They appear in the code four times. I **recommend** that they be put into a member function.

2021-09-15 01:42 UTC, PetrilloAtWork commented on sbndcode/OpDetSim/DigiPMTSBNDAlg.cc
> +    size_t max = time_bin + pulsesize < wave.size() ? time_bin + pulsesize : wave.size();
I **suggest** you use parentheses. The expression is correct, but I had to check a reference to verify the priorities between `?:`, `+` and `<`... I know I expressly forget operator priorities.
By the way, since you don't intend to change `max`, you can declare it `const`.

2021-09-15 01:42 UTC, PetrilloAtWork commented on sbndcode/OpDetSim/PMTAlg/PMTGainFluctuations1Dynode_tool.cc
> +  double fRefGain;
A comment that this is the gain on the first dynode is due.
Also, if possible, a more explicit name for this variable would also help: `fRefGain` was in my mind 10⁷, the nominal gain, which as such is also a reference gain.

2021-09-15 13:53 UTC, fjnicolas commented on sbndcode/OpDetSim/PMTAlg/pmtgainfluctuations_config.fcl
> +  VoltageDistribution:    [ 17.4, 3.4, 5.0, 3.33, 1.67, 1.0, 1.2, 1.5, 2.2, 3.0 ]
Agree. I added some references and a TODO in the configuration fhicl file

2021-09-15 14:02 UTC, fjnicolas commented on sbndcode/OpDetSim/PMTAlg/PMTGainFluctuations1Dynode_tool.cc
> +  unsigned int fGain;
Changed with commit 
971f9b5

2021-09-15 14:19 UTC, fjnicolas commented
Changes after 971f9b5 (from suggestions from @PetrilloAtWork):
- Rename `fRegGain` variable to `fDynodeGain` in `opdet::PMTGainFluctuations1Dynode_tool.cc`
- Make `GainFluctuationsPset` a `fhicl::OptionalDelegatedParameter` and rename it to `GainFluctuationsParams` (in `DigiPMTSBNDSBNDAlg`)
- Use `art::ToolConfigTable<Config>`  for variable initialization in `opdet::PMTGainFluctuations1Dynode_tool.cc`
- Modified `AddSPE` function

2021-09-15 14:58 UTC, lpaulucc approved these changes
The code looks ok. I have no comments other than the ones already presented by Gianluca and Iker

2021-09-15 23:42 UTC, PetrilloAtWork approved these changes
Thank you for your changes, Francisco.
I apologise I had not notice a coding detail in the first review; I am going to point it now, but since it's past the deadline, you can decide to just ignore it.

It is good to declare constant the methods which do not change the state of an object.
For example, `opdet::DigiPMTSBNDAlg::AddSPE()` does not; it changes a waveform, but that is passed as argument.
Another example is currently the fluctuator tool: effectively, `double PMTGainFluctuations1Dynode::GainFluctuation()` also does not change the state of the object and could be declared `const`. Here the choice is a bit more complicate, because to do that you would also need to change the base class interface, forcing the future implementations to be "const" too. The call is yours.

Anyway, formal approval here.

2021-09-15 23:42 UTC, PetrilloAtWork commented on sbndcode/OpDetSim/DigiPMTSBNDAlg.hh
>      void AddSPE(size_t time_bin, std::vector<double>& wave); // add single pulse to auxiliary waveform
```suggestion
    void AddSPE(size_t time_bin, std::vector<double>& wave) const; // add single pulse to auxiliary waveform
```

2021-09-15 23:42 UTC, PetrilloAtWork commented on sbndcode/OpDetSim/PMTAlg/PMTGainFluctuations1Dynode_tool.cc
> +  double DynodeGain(unsigned int dynstage);
```suggestion
  double DynodeGain(unsigned int dynstage) const;
```

2021-09-15 23:51 UTC, ikatza approved these changes

2021-09-17 10:52 UTC, pgreen135 commented
trigger build

2021-09-17 10:52 UTC, FNALbuild commented
CI build for LArSoft on slf7 for c7:prof is in progress -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/12571&builds=)

2021-09-17 10:53 UTC, FNALbuild commented
CI build for LArSoft on slf7 for e20:prof is in progress -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/12572&builds=)

2021-09-17 10:53 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c7:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/12571&builds=)

2021-09-17 10:53 UTC, FNALbuild commented
CI build for SBND on slf7 for c7:prof is in progress -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/7186&builds=)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/12571&builds=)

2021-09-17 11:13 UTC, FNALbuild commented
:warning: CI build for SBND Warning at phase ci_tests SBND on slf7 for c7:prof - ignored warnings for build -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/7186&builds=)

:rotating_light: For more details about the warning phase, check the [ci_tests SBND phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/7186&platform=Linux%203.10.0-1160.31.1.el7.x86_64&phase=ci_tests&buildtype=slf7%20c7:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/12571&builds=)

2021-09-17 11:20 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for e20:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/12572&builds=)

2021-09-17 11:20 UTC, FNALbuild commented
CI build for SBND on slf7 for e20:prof is in progress -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/7188&builds=)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/12572&builds=)

2021-09-17 12:00 UTC, FNALbuild commented
:warning: CI build for SBND Warning at phase ci_tests SBND on slf7 for e20:prof - ignored warnings for build -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/7188&builds=)

:rotating_light: For more details about the warning phase, check the [ci_tests SBND phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/7188&platform=Linux%203.10.0-1160.31.1.el7.x86_64&phase=ci_tests&buildtype=slf7%20e20:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/12572&builds=)

2021-09-17 12:23 UTC, merged