Add further rollup-less fcls
SBNSoftware/sbndcode pull request #234
Opened 2021-12-02 10:20 UTC by henrylay97

As requested by @jzennamo in yesterday's RM meeting. A further 5 fcls for running g4 without rollup.

2021-12-02 17:12 UTC, marcodeltutto requested changes
Thanks for adding these @henrylay97! They look good, I just have a couple of comments. Maybe I am missing something but I think we can have the fcls include the previous ones, so they are easier to maintain.

2021-12-02 17:12 UTC, marcodeltutto commented on sbndcode/JobConfigurations/standard/gen/corsika/prodcorsika_proton_intime_filter_no_shower_rollup.fcl
> +
Can this file inherit from `prodcorsika_proton_intime_filter.fcl`?
```
#include "prodcorsika_proton_intime_filter.fcl"
services.ParticleListAction.keepEMShowerDaughters: true
```
That would be easier to maintain.

Do we also need the one with SCE?

2021-12-02 17:12 UTC, marcodeltutto commented on sbndcode/JobConfigurations/standard/gen/overlay/prodoverlay_corsika_cosmics_proton_genie_rockbox_sbnd_no_shower_rollup.fcl
> +services.ParticleListAction.keepEMShowerDaughters: true
Can this file inherit from `prodoverlay_corsika_cosmics_proton_genie_rockbox_sbnd.fcl`?
```
#include "prodoverlay_corsika_cosmics_proton_genie_rockbox_sbnd.fcl"
services.ParticleListAction.keepEMShowerDaughters: true
```
That would be easier to maintain.

2021-12-03 09:35 UTC, henrylay97 commented
Thanks @marcodeltutto you're totally right about them inheriting from the previous fcls.

As for whether we need the sce versions, I'll let @jzennamo wade in on that, this was just the list he sent me from production requests.

2021-12-03 15:11 UTC, marcodeltutto approved these changes
Thanks @henrylay97! Looks good. If these are the fcls that @jzennamo requested, they look good to me.

2021-12-03 15:12 UTC, jzennamo commented
Oh man, let me check, I might have screwed up the fcls. Likely good catch @marcodeltutto  🤦

2021-12-03 15:15 UTC, jzennamo commented
Great catch @marcodeltutto I did want `prodcorsika_proton_intime_filter_sce.fcl`... Sorry for the misdirect @henrylay97!

2021-12-06 09:25 UTC, henrylay97 commented
What about for the prodoverlay file? @jzennamo

2021-12-06 10:40 UTC, pgreen135 commented
@henrylay97 I think that wants to be the sce version too, as we are using those for all the other samples

2021-12-06 14:59 UTC, jzennamo commented
life saver! Yes, we'll need a SCE version of `prodoverlay_corsika_cosmics_proton_genie_rockbox_sbnd.fcl` which I thought was SCE enabled

2021-12-06 16:23 UTC, henrylay97 commented
Ah I was purely going by name. I'll take a look and push these extras :)

2021-12-06 16:42 UTC, henrylay97 commented
Okay so just to update again:
- The file `prodcorsika_proton_intime_filter_no_shower_rollup.fcl` has been replaced with `prodcorsika_proton_intime_filter_sce_no_shower_rollup.fcl`
- The file `prodoverlay_corsika_cosmics_proton_genie_rockbox_sce.fcl` has been added so we can also then add `prodoverlay_corsika_cosmics_proton_genie_rockbox_sce_no_shower_rollup.fcl`

2021-12-06 16:42 UTC, henrylay97 commented
I think @jzennamo this provides the necessary fcls now

2021-12-07 16:53 UTC, jzennamo approved these changes
Thank you so much for pulling these together!

2021-12-07 17:12 UTC, merged