Patch for CRT error where AuxDets can't be found
SBNSoftware/sbndcode pull request #240
Opened 2021-12-10 23:39 UTC by henrylay97

**Very** intermittent error found by @jzennamo. Also thanks to @marcodeltutto and @wesketchum for help with debugging.

```
---- ChannelMap BEGIN
  Can't find AuxDet for position (132.794,-376.746,-8.4112)
  The above exception was thrown while processing module GenericCRT/genericcrt run: 1 subRun: 0 event: 84
---- ChannelMap END
```

This error is being thrown in the [ChannelMapAlg](https://github.com/LArSoft/larcorealg/blob/develop/larcorealg/Geometry/ChannelMapAlg.cxx) but this PR overrides the relevant functions in sbndcode's ChannelMapSBNDAlg.

Instead of throwing an exception the same error message is now outputted as a debugging message and the function returns `UINT_MAX` as the channel ID.

A catch is added at the detsim stage and in a detsim analysis module to skip channels with the ID `UINT_MAX`.

The underlying bug is worth investigating further and @ilepetic can probably comment further.

Due the rare nature of this bug I haven't been able to consistently reproduce it to test these changes on, however I have made some tests of the detsim stage where I forcibly return `UINT_MAX` and the catch works fine.

2021-12-13 20:06 UTC, marcodeltutto requested changes
Looks great, thanks so much @hlay! I just have a couple of comments.

Could you also remove this exception [here](https://github.com/SBNSoftware/sbndcode/blob/c569938ccabe635bcae6382832d65898c96ffe2c/sbndcode/CRT/CRTChannelMapAlg.cxx#L125) and add a debug message as you did in `ChannelMapSBNDAlg`? Otherwise, if someone uses `AuxDetGeometryCore` that will throw an exception.

2021-12-13 20:06 UTC, marcodeltutto commented on sbndcode/CRT/CRTDetSim_module.cc
> +    if(adsc.AuxDetSensitiveID() == UINT_MAX)
Can you please also add a LOG_WARNING here with something like "Skipping AuxDetSensitiveID with bad channel number." This happens rarely so it won't clog our log files, but at least we see it and remember it's something we'll have to fix.

2021-12-13 20:06 UTC, marcodeltutto commented on sbndcode/CRT/CRTAna/CRTDetSimAna_module.cc
> +      if(adsc.AuxDetSensitiveID() == UINT_MAX)
Similarly here

2021-12-14 11:39 UTC, henrylay97 commented
Thanks @marcodeltutto, all great suggestions. I've followed up in the above commits :+1:

2021-12-14 12:43 UTC, pgreen135 commented
trigger build

2021-12-14 12:43 UTC, pgreen135 commented
trigger build

2021-12-14 12:45 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for e20:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/13923&builds=)

2021-12-14 12:45 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c7:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/13924&builds=)

2021-12-14 13:10 UTC, FNALbuild commented
:warning: CI build for SBND Warning at phase ci_tests SBND on slf7 for e20:prof - ignored warnings for build -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/8271&builds=)

:rotating_light: For more details about the warning phase, check the [ci_tests SBND phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/8271&platform=Linux%203.10.0-1160.45.1.el7.x86_64&phase=ci_tests&buildtype=slf7%20e20:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/13923&builds=)

2021-12-14 13:20 UTC, FNALbuild commented
:warning: CI build for SBND Warning at phase ci_tests SBND on slf7 for c7:prof - ignored warnings for build -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/8272&builds=)

:rotating_light: For more details about the warning phase, check the [ci_tests SBND phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/8272&platform=Linux%203.10.0-1160.31.1.el7.x86_64&phase=ci_tests&buildtype=slf7%20c7:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/13924&builds=)

2021-12-14 14:42 UTC, marcodeltutto approved these changes
Looks good, thank you!

2021-12-14 15:27 UTC, ilepetic approved these changes

2021-12-15 09:55 UTC, merged