Feature/eyandel trigger
SBNSoftware/sbndcode pull request #296
Opened 2022-09-07 16:33 UTC by eyandel

- Made some modules to combine CRT and PMT simulated fragments into one event. 
- Put CRT software trigger metrics module @mstancar made for sbndaq into sbndcode (needs to include [sbnobj PR #62](https://github.com/SBNSoftware/sbnobj/pull/62) as well). 
- Make "T1 reset" events for CRT boards with no hits in an event to avoid missing fragments.

2022-09-07 20:51 UTC, lynnt-uchicago commented
Hi Erin!! thanks for all the work of adding/removing files!! For the MetricsProducer module, are the pmt metrics more or less copy/pasted over? from a quick look it didn't look like you changed anything about the structure. is the eventual plan to remove the separate PMT software trigger module and only use the MetricsProducer module?

2022-09-07 20:54 UTC, lynnt-uchicago commented on sbndcode/Trigger/run_metricproducer.fcl
> +physics.producers.SoftwareTriggerMetric.BeamWindowStart: 1650000
if the eventual plan is to have both the CRT and the PMTs in this same "SoftwareTriggerMetric" producer, maybe we need to specify CRTBeamWindow and PMTBeamWindow?

2022-09-07 21:37 UTC, henrylay97 approved these changes
Looks fab Erin, thanks for doing this. A lot of this is outside of my scope. I understand what you're doing with the combining of the simulated fragment producers and the production of a CRT fragment regardless of activity, all looks great. 

I've included a few comments but they're all totally naive and ignorable / stylistic so from my side its good to go.

2022-09-07 21:37 UTC, henrylay97 commented on sbndcode/Commissioning/HitDumper_module.cc
> +  freadcrtSoftTrigger= p.get<bool>("readcrtSoftTrigger",false);
Sanity check... pmt soft trigger defaults true, crt defaults false... Deliberate?

2022-09-07 21:37 UTC, henrylay97 commented on sbndcode/Commissioning/fcls/detsim_comm_fhicldump.out
> +# Produced from 'fhicl-dump' using:
Naive question again, what's the reason for committing this dump output?

2022-09-07 21:37 UTC, henrylay97 commented on sbndcode/Commissioning/HitDumper_module.cc
> +  int    _crtSoftTrigger_hitsperplane[7];       ///< Number of (very low level) CRT hits per plane
Being picky here... Even though this will always be 7, I'm not a fan of hard coded numbers. Personally I would code this as a std::vector which is resized by using the geom service to get the number of planes.

2022-09-07 21:37 UTC, henrylay97 commented on sbndcode/Commissioning/HitDumper_module.cc
> +      for (int i=0; i<7; i++){
as with earlier comment this would allow you to avoid this hard coding too

2022-09-07 21:37 UTC, henrylay97 commented on sbndcode/Commissioning/HitDumper_module.cc
> +  for (int i=0; i<7; i++){
and here, crops up in other modules as well, I think you're probably going to ignore me (as I probably would to ;) ) so I won't comment each one.

2022-09-07 21:37 UTC, henrylay97 commented on sbndcode/Trigger/ArtdaqFragmentProducer_module.cc
> +            adc = 4089;
Out of interest why 4089? Would threshold not be 4095?

2022-09-07 21:37 UTC, henrylay97 commented on sbndcode/Trigger/MetricProducer_module.cc
> +
Quite a lot of places, like here, where cleaning up the formatting would make it a lot more readable, again not really something for now.

2022-09-08 17:13 UTC, eyandel commented
> Hi Erin!! thanks for all the work of adding/removing files!! For the MetricsProducer module, are the pmt metrics more or less copy/pasted over? from a quick look it didn't look like you changed anything about the structure. is the eventual plan to remove the separate PMT software trigger module and only use the MetricsProducer module?

Yes everything is pretty much just copied over. I think ideally we will move to just using the one module so that we can save time by not opening fragments multiple times. This is just the first working attempt at that for now. It will need a bit more work to get the structure to fit together more efficiency I think.

2022-09-08 17:16 UTC, eyandel commented on sbndcode/Trigger/run_metricproducer.fcl
> +physics.producers.SoftwareTriggerMetric.BeamWindowStart: 1650000
I agree. I believe they are currently separate but not named well due to the fact that I just took them from their separate codes. This will be one of the things we should update when we start improving this module.

2022-09-08 17:18 UTC, eyandel commented on sbndcode/Commissioning/HitDumper_module.cc
> +  freadcrtSoftTrigger= p.get<bool>("readcrtSoftTrigger",false);
An unfortunate consequence of multiple people writing the code and me stitching it together. I think I defaulted the new one to true since the products for it were not in sbnobj yet and I didn't want to break anything if someone updates and doesn't know these new products are there.

2022-09-08 17:22 UTC, eyandel commented on sbndcode/Commissioning/fcls/detsim_comm_fhicldump.out
> +# Produced from 'fhicl-dump' using:
it's deleted now

2022-09-08 17:24 UTC, eyandel commented on sbndcode/Commissioning/HitDumper_module.cc
> +  int    _crtSoftTrigger_hitsperplane[7];       ///< Number of (very low level) CRT hits per plane
I agree. However, I mostly was just moving stuff over from what Michelle made in sbndaq and she hardcoded this. I think we should fix it there first before changing it here, since I want this to be basically as close to the daq version as possible. But yes this will hopefully be changed in the future.

2022-09-08 17:26 UTC, eyandel commented on sbndcode/Commissioning/HitDumper_module.cc
> +  for (int i=0; i<7; i++){
Hopefully these will all be changed eventually! so notes about where we need to change this are helpful thank you.

2022-09-08 17:26 UTC, eyandel commented on sbndcode/Trigger/ArtdaqFragmentProducer_module.cc
> +            adc = 4089;
data is at 4089 for some reason. I don't know why but that's what we see.

2022-09-08 17:27 UTC, eyandel commented on sbndcode/Trigger/MetricProducer_module.cc
> +
agreed. and again notes on where this work needs to happen are welcome!

2022-09-08 17:42 UTC, lynnt-uchicago approved these changes
generally looks good!! confirmed that my changes to the software trigger on the branch `/feature/lynnt_pmt_trig` build and look fine, up to you if you want to add the changes from that (mainly fcl parameter changes) to this commit or save for a future PR

2022-09-08 17:48 UTC, henrylay97 commented on sbndcode/Commissioning/HitDumper_module.cc
> +  freadcrtSoftTrigger= p.get<bool>("readcrtSoftTrigger",false);
Fab, just checking :)

2022-09-08 17:48 UTC, henrylay97 commented on sbndcode/Commissioning/fcls/detsim_comm_fhicldump.out
> +# Produced from 'fhicl-dump' using:
ace

2022-09-08 17:49 UTC, henrylay97 commented on sbndcode/Commissioning/HitDumper_module.cc
> +  int    _crtSoftTrigger_hitsperplane[7];       ///< Number of (very low level) CRT hits per plane
Okay that's fair. Worth adding a comment above this line maybe to point us at a TODO for future.

2022-09-08 17:51 UTC, henrylay97 commented on sbndcode/Trigger/ArtdaqFragmentProducer_module.cc
> +            adc = 4089;
Weird, okay!

2022-09-08 21:24 UTC, henrylay97 requested changes
Hi both @lynnt-uchicago @eyandel 

In doing some work on the binary file stuff I have come across something that is important to this PR. I was getting seg faults when trying to properly serialize the waveform data from these simulated CAEN fragments. There is a field in the header called eventSize which is used to guide how big the waveform is that we're reading out. Could be hard coded but as I note in a comment that is a super bad idea when we're playing with pointers & casts so I really don't want to do that.

What we need to do is work out the eventSize in this module and fill this field so it can be used in the serialisation (but also for things like the EventAna or MultiDump modules, they both use this field and are also currently seg faulting when reading waveforms from these sim files).

2022-09-08 21:24 UTC, henrylay97 commented on sbndcode/Trigger/ArtdaqFragmentProducer_module.cc
> +  uint32_t wfm_length = 5120; // ~10us, 2ns tick
These (especially `wfm_length`) should not be hardcoded. Unlike the other example I think this is something we might want to change now Lynn Tung.

2022-09-08 21:24 UTC, henrylay97 commented on sbndcode/Trigger/ArtdaqFragmentProducer_module.cc
> +      header_ptr->triggerTimeTag = triggerTimeTagVal;  // ns // set timetag as random value for event
We need to fill the event size here. Its the only handle we have to read back the fragments from binary without assuming a set length of the waveform. As we're dealing with a lot of scary pointers and casting them I don't want to hardcode any sizes. We may also need other header field filled too but for now this one is the deal breaker.

2022-09-08 21:48 UTC, henrylay97 commented on sbndcode/Trigger/ArtdaqFragmentProducer_module.cc
> +      header_ptr->triggerTimeTag = triggerTimeTagVal;  // ns // set timetag as random value for event
I believe that the eventSize should be calculable as:

`wfm_length * (nChannelsFrag+1) / 2. + sizeof(CAENV1730EventHeader)`

The product `wfm_length * (nChannelsFrag+1)` gives you the number of waveform data points. We divide by two purely because the data points are saved as `uint16_t`'s and this field is a `uint32_t`. We then also must account for the header as it is stored before in the memory.

2022-09-09 20:35 UTC, eyandel reviewed
should include all requested pmt changes from @henrylay97. Files made from this branch ran in the daq and gave sensible multidump output (and no seg faults seen). The hardcoded waveform length is now a fhicl parameter (which is what it is in the actual hardware as well).

2022-09-12 01:57 UTC, henrylay97 approved these changes
Looks great, thanks @eyandel!

2022-09-13 08:49 UTC, fjnicolas commented
trigger build SBNSoftware/sbnobj#62

2022-09-13 08:52 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for e20:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/16691&builds=)

2022-09-13 08:53 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c7:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/16690&builds=)

2022-09-13 09:03 UTC, FNALbuild commented
:x: CI build for SBND Failed at phase build SBND on slf7 for c7:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/10198&builds=)

:rotating_light: For more details about the failed phase, check the [build SBND phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/10198&platform=Linux%203.10.0-1160.71.1.el7.x86_64&phase=build&buildtype=slf7%20c7:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/16690&builds=)

2022-09-13 09:34 UTC, FNALbuild commented
:warning: CI build for SBND Warning at phase ci_tests SBND on slf7 for e20:prof - ignored warnings for build -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/10197&builds=)

:rotating_light: For more details about the warning phase, check the [ci_tests SBND phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/10197&platform=Linux%203.10.0-1160.71.1.el7.x86_64&phase=ci_tests&buildtype=slf7%20e20:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/16691&builds=)

2022-09-13 13:13 UTC, fjnicolas commented
@eyandel can you have a look at the c7 compiling error (https://dbweb8.fnal.gov:8443/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/10198&platform=Linux%203.10.0-1160.71.1.el7.x86_64&phase=build&buildtype=slf7%20c7:prof)?

2022-09-13 14:31 UTC, henrylay97 reviewed
The failure was an unused variable complaint which c7 is good at catching.

The variables were actually defined twice. I've suggested two commits which will remove the global instance, keep the local and rename the local to avoid them looking like global.

2022-09-13 14:31 UTC, henrylay97 commented on sbndcode/Trigger/MetricProducer_module.cc
> +  art::EventNumber_t fEvent;
```suggestion
```

2022-09-13 14:31 UTC, henrylay97 commented on sbndcode/Trigger/MetricProducer_module.cc
> +  if (fVerbose) std::cout << "Processing: Run " << fRun << ", Event " << fEvent << std::endl;
```suggestion
  int run = evt.run();
  art::EventNumber_t event_num = evt.event();

  if (fVerbose) std::cout << "Processing: Run " << run << ", Event " << event_num << std::endl;
```

2022-09-13 15:30 UTC, eyandel commented on sbndcode/Trigger/MetricProducer_module.cc
> +  if (fVerbose) std::cout << "Processing: Run " << fRun << ", Event " << fEvent << std::endl;
oh sorry I just saw this. I did the opposite (keep the global and delete the redefinition) , which I think should also resolve the issue. Is there a reason I should do your suggestion instead?

2022-09-13 15:34 UTC, henrylay97 commented on sbndcode/Trigger/MetricProducer_module.cc
> +  if (fVerbose) std::cout << "Processing: Run " << fRun << ", Event " << fEvent << std::endl;
Absolutely fine, no particular reason no, I suppose as they're not needing to be accessed globally ever then that was my thinking. Yours works absolutely fine and other changes in that commit look fine too.

2022-09-13 15:41 UTC, fjnicolas commented
thanks @eyandel @henrylay97! It will be included in the next release

2022-09-13 15:42 UTC, fjnicolas commented
trigger build SBNSoftware/sbnobj#62

2022-09-13 15:45 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for e20:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/16693&builds=)

2022-09-13 16:17 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c7:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/16694&builds=)

2022-09-13 16:20 UTC, FNALbuild commented
:warning: CI build for SBND Succeeded with warning at phase build on slf7 for e20:prof - ignored warnings for build -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/10200&builds=)


parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/16693&builds=)

2022-09-13 17:10 UTC, FNALbuild commented
:warning: CI build for SBND Warning at phase ci_tests SBND on slf7 for c7:prof - ignored warnings for build -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/10201&builds=)

:rotating_light: For more details about the warning phase, check the [ci_tests SBND phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/10201&platform=Linux%203.10.0-1160.71.1.el7.x86_64&phase=ci_tests&buildtype=slf7%20c7:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/16694&builds=)

2022-09-14 16:41 UTC, henrylay97 commented
If we could hold merging this for now, I think I might need a further edit to the CAEN sim fragment production. I'll update by the end of the day if not before, would be nice to save making a small extra PR!

2022-09-14 16:58 UTC, henrylay97 requested changes

2022-09-14 16:58 UTC, henrylay97 commented on sbndcode/Trigger/ArtdaqFragmentProducer_module.cc
> +  uint32_t eventSizeVal = ((wfm_length * (nChannelsFrag+1)) / 2.) + sizeof(sbndaq::CAENV1730EventHeader);
Aha, found the typo... We weren't dividing the event header size by 4.

```suggestion
  uint32_t eventSizeVal = ((wfm_length * (nChannelsFrag+1)) * sizeof(uint16_t) + sizeof(sbndaq::CAENV1730EventHeader)) / sizeof(uint32_t);
```

I don't know why but this field is stored in quad bytes. Not bytes. This is why we divide the length * channels chunk by 2 (each entry is 2 bytes) but we also need to do the same with the size of the event header, we want it in quad bytes, `sizeof` returns bytes.

I've changed the way we write it to try and make it more readable... Calculate the whole thing in bytes, then divide by the size of a quadbyte (4) but this is, in effect, the same as my suggestion the other day.

2022-09-14 16:59 UTC, henrylay97 commented on sbndcode/Trigger/ArtdaqFragmentProducer_module.cc
> +  uint32_t eventSizeVal = ((wfm_length * (nChannelsFrag+1)) / 2.) + sizeof(sbndaq::CAENV1730EventHeader);
@eyandel I will test this with the full system after lunch

2022-09-14 21:42 UTC, henrylay97 approved these changes
Sorry for the delay folks. This change now reflects the original intent and works through the full DAQ - Sim chain as it currently stands!

2022-09-14 21:51 UTC, henrylay97 commented
trigger build SBNSoftware/sbnobj#62

2022-09-14 22:29 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for e20:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/16724&builds=)

2022-09-14 22:30 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c7:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/16723&builds=)

2022-09-14 23:09 UTC, FNALbuild commented
:warning: CI build for SBND Warning at phase ci_tests SBND on slf7 for e20:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/10220&builds=)

:rotating_light: For more details about the warning phase, check the [ci_tests SBND phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/10220&platform=Linux%203.10.0-1160.71.1.el7.x86_64&phase=ci_tests&buildtype=slf7%20e20:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/16724&builds=)

2022-09-14 23:27 UTC, FNALbuild commented
:warning: CI build for SBND Warning at phase ci_tests SBND on slf7 for c7:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/10221&builds=)

:rotating_light: For more details about the warning phase, check the [ci_tests SBND phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/10221&platform=Linux%203.10.0-1160.71.1.el7.x86_64&phase=ci_tests&buildtype=slf7%20c7:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/16723&builds=)

2022-09-20 08:06 UTC, merged