Added option in configuration to enable and disable HNL ThreeBodyAnis…
SBNSoftware/sbndcode pull request #324
Opened 2023-03-15 16:14 UTC by LuisPelegrina

…otropies

2023-04-11 09:17 UTC, jicrespo requested changes

2023-04-11 09:17 UTC, jicrespo commented on sbndcode/JobConfigurations/standard/gen/MeVPrtl/hnl_config.fcl
> +  DecayIsThreeBodyAnisotropic: true
I am not in favor of enabling a 3-body decay option that is not relevant for the current channel (2-body decay into muon + pion) since this can be confusing for future users. I suggest creating a specific config for the 3-body case with that option enabled.

2023-04-26 09:58 UTC, jicrespo approved these changes

2023-04-26 09:58 UTC, jicrespo commented on sbndcode/OpT0Finder/SBNDOpT0Finder_module.cc
This file is included in the commit by mistake?

2023-06-06 18:16 UTC, rodralva approved these changes

2023-06-07 15:19 UTC, merged