Update beam flux from config J to K
SBNSoftware/sbndcode pull request #363
Opened 2023-07-06 15:24 UTC by VCLanNguyen

Update from flux config J-v1 to config K-v1 
What’s new: 
New flux production on gpvm
Kaon weight is applied with a stand alone code and does not have MiniBooNE dependency 

Validation can be found on docdc ??

2023-07-06 15:32 UTC, VCLanNguyen commented
trigger

2023-07-06 15:39 UTC, RachelCoackley commented
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_75_02 SBNSoftware/sbncode@v09_75_02 SBNSoftware/sbnanaobj@v09_21_02 SBNSoftware/sbnobj@v09_17_03

2023-07-06 16:12 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c7:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/19928&builds=)

2023-07-06 16:12 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for e20:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/19927&builds=)

2023-07-06 17:03 UTC, FNALbuild commented
:x: CI build for SBND Failed at phase ci_tests SBND on slf7 for e20:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/12207&builds=)

:rotating_light: For more details about the failed phase, check the [ci_tests SBND phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/12207&platform=Linux%203.10.0-1160.88.1.el7.x86_64&phase=ci_tests&buildtype=slf7%20e20:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/19927&builds=)

2023-07-06 17:30 UTC, FNALbuild commented
:x: CI build for SBND Failed at phase ci_tests SBND on slf7 for c7:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/12206&builds=)

:rotating_light: For more details about the failed phase, check the [ci_tests SBND phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/12206&platform=Linux%203.10.0-1160.88.1.el7.x86_64&phase=ci_tests&buildtype=slf7%20c7:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/19928&builds=)

2023-07-07 12:51 UTC, RachelCoackley commented
The CI tests are coming up failed due to nucosmics_gen_quick_test_sbndcode having an error in data production. I ran the CI tests again (https://dbweb8.fnal.gov:8443/LarCI/app/ns:sbnd/build_detail/phase_details?build_id=sbnd_ci/12217&platform=Linux%203.10.0-1160.88.1.el7.x86_64&phase=ci_tests&buildtype=slf7%20e20:prof) and got the same result. It looks like it's not being able to find a flux file, @VCLanNguyen would you be able to have a quick look? Thanks!

2023-07-07 13:49 UTC, marcodeltutto requested changes

2023-07-07 13:49 UTC, marcodeltutto commented on sbndcode/LArSoftConfigurations/gen/genie_sbnd.fcl
> +  @table::sbnd_flux_bnb_nu_Jv1
This should have "K", no "J"

2023-07-07 14:01 UTC, VCLanNguyen commented
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_75_02 SBNSoftware/sbncode@v09_75_02 SBNSoftware/sbnanaobj@v09_21_02 SBNSoftware/sbnobj@v09_17_03

2023-07-07 14:01 UTC, VCLanNguyen commented on sbndcode/LArSoftConfigurations/gen/genie_sbnd.fcl
> +  @table::sbnd_flux_bnb_nu_Jv1
fixed the typo!

2023-07-07 14:12 UTC, marcodeltutto approved these changes

2023-07-07 14:34 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for e20:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/19951&builds=)

2023-07-07 15:28 UTC, FNALbuild commented
:warning: CI build for SBND Warning at phase ci_tests SBND on slf7 for e20:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/12220&builds=)

:rotating_light: For more details about the warning phase, check the [ci_tests SBND phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/12220&platform=Linux%203.10.0-1160.88.1.el7.x86_64&phase=ci_tests&buildtype=slf7%20e20:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/19951&builds=)

2023-07-07 15:43 UTC, FNALbuild commented
:warning: CI build for SBND Warning at phase ci_tests SBND on slf7 for c7:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/12219&builds=)

:rotating_light: For more details about the warning phase, check the [ci_tests SBND phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/12219&platform=Linux%203.10.0-1160.88.1.el7.x86_64&phase=ci_tests&buildtype=slf7%20c7:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/19950&builds=)

2023-07-07 16:38 UTC, VCLanNguyen commented
CI picked up fcl changes 

```
84: ===================================================================================================================================
85: 38c38
86: <             "gsimple_bnb_neutrino_sbnd_v2_wvtxt_20210322_*.root"
87: ---
88: >             "gsimple_april07_baseline_*_redecay_wkaonwgh.root"
89: 40c40
90: <          FluxSearchPaths: "/cvmfs/sbnd.osgstorage.org/pnfs/fnal.gov/usr/sbnd/persistent/stash/fluxFiles/bnb/BooNEtoGSimple/configJ-v1/feb2023/neutrinoMode/"
91: ---
92: >          FluxSearchPaths: "/cvmfs/sbnd.osgstorage.org/pnfs/fnal.gov/usr/sbnd/persistent/stash/fluxFiles/bnb/BooNEtoGSimple/configK-v1/july2023/neutrinoMode"
93: ===================================================================================================================================
```

2023-07-07 16:43 UTC, VCLanNguyen commented
Expected [nucosmics_caf_quick_test_sbndcode](https://dbweb8.fnal.gov:8443/LarCI/app/ns:SBND/build_detail/test_details?build_id=sbnd_ci/12219&platform=Linux%203.10.0-1160.88.1.el7.x86_64&buildtype=slf7%20c7:prof&phase=ci_tests&test=nucosmics_caf_quick_test_sbndcode) to be different given new flux files so probably different nu interactions

2023-07-07 16:51 UTC, fjnicolas commented
Thanks @VCLanNguyen! All looks good from my part. I'm assuming you mean [nucosmics_gen_quick_test_sbndcode](https://dbweb8.fnal.gov:8443/LarCI/app/ns:SBND/build_detail/test_details?build_id=sbnd_ci/12220&platform=Linux%203.10.0-1160.88.1.el7.x86_64&buildtype=slf7%20e20:prof&phase=ci_tests&test=nucosmics_gen_quick_test_sbndcode)

2023-07-12 16:34 UTC, merged