Feature/apapadop sbnd systtools
SBNSoftware/sbndcode pull request #379
Opened 2023-07-25 23:57 UTC by afropapp13

feature branch containing the ffcl's for implementation of systtools in the sbnd workflow

2023-08-04 15:39 UTC, fjnicolas commented
hi @afropapp13! is this PR ready to go? who would you like to add as reviewers?? thanks!

2024-01-24 18:04 UTC, fjnicolas commented
trigger build

2024-01-24 18:07 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for e26:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/21553&builds=)

2024-01-24 18:08 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/21554&builds=)

2024-01-24 18:24 UTC, FNALbuild commented
:x: CI build for SBND Failed at phase unit_test SBND on slf7 for e26:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/13416&builds=)

:rotating_light: For more details about the failed phase, check the [unit_test SBND phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/13416&platform=Linux%203.10.0-1160.102.1.el7.x86_64&phase=unit_test&buildtype=slf7%20e26:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/21553&builds=)

2024-01-24 18:26 UTC, FNALbuild commented
:x: CI build for SBND Failed at phase unit_test SBND on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/13417&builds=)

:rotating_light: For more details about the failed phase, check the [unit_test SBND phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/13417&platform=Linux%203.10.0-1160.102.1.el7.x86_64&phase=unit_test&buildtype=slf7%20c14:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/21554&builds=)

2024-02-01 17:35 UTC, fjnicolas commented
trigger build

2024-02-01 17:39 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for e26:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/21676&builds=)

2024-02-01 17:39 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/21677&builds=)

2024-02-01 17:57 UTC, FNALbuild commented
:x: CI build for SBND Failed at phase unit_test SBND on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/13487&builds=)

:rotating_light: For more details about the failed phase, check the [unit_test SBND phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/13487&platform=Linux%203.10.0-1160.102.1.el7.x86_64&phase=unit_test&buildtype=slf7%20c14:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/21677&builds=)

2024-02-02 09:23 UTC, henrylay97 requested changes
Hi Afro, thanks for taking another look at this. I have a couple of requests before we merge this.

Firstly, the config directory contains the files used to make the original version of the `systtools_*` file. These should either be removed or replaced with the ones actually used to generate the newer version. (I reckon just removed is fine, the relevant configs are contained in the relevant ICARUS releases and should in future be moved to sbncode anyway).

2024-02-02 09:23 UTC, henrylay97 commented on sbndcode/JobConfigurations/standard/caf/SystTools/configs/config_All_sbnd_v1.fcl
This, and similar other files should be removed or updated to reflect the actual configuration used to generate the files.

2024-02-02 09:23 UTC, henrylay97 commented on sbndcode/JobConfigurations/standard/caf/cafmakerjob_sbnd_sce_systtools.fcl
Looks like this could be better done by inheriting the sce fcl? Lots of duplication & therefore extra points of maintenance?

2024-02-02 09:23 UTC, henrylay97 commented on sbndcode/JobConfigurations/standard/caf/cafmakerjob_sbnd_systtools.fcl
Same comment. Can this just inherit?

2024-02-02 09:23 UTC, henrylay97 commented on sbndcode/JobConfigurations/standard/caf/syst_params_sbnd_v2.fcl
Something has gone wrong with the copying of this! Compare to what the original v1 file looks like and what the v2 file looks like in `icaruscode`.

2024-02-14 16:48 UTC, henrylay97 requested changes
Still got some queries and requests here @afropapp13 sorry!

Some of these fcls will not work, the systtools producer is used but not defined anywhere in their chain. 

Other fcls do not do what they say in the name  / appear completely redundant?

2024-02-14 16:48 UTC, henrylay97 commented on sbndcode/JobConfigurations/standard/caf/SystTools/configs/config_All_sbnd_v2.fcl
> +#include "config_GENIEReWeightMultisim_sbnd_v2.fcl"
Fab thanks!

2024-02-14 16:48 UTC, henrylay97 commented on sbndcode/JobConfigurations/standard/caf/SystTools/configs/config_GENIEReWeightMultisigma_sbnd_v2.fcl
> +    instance_name: "ICARUS_v2_multisigma"
Ideally we'd have renamed these and then reproduced the `syst_params` file with updated names. But given the long term plan is to move to storing these at an SBN-level this is probably worth leaving, might help remind us.

2024-02-14 16:48 UTC, henrylay97 commented on sbndcode/JobConfigurations/standard/caf/cafmakerjob_sbnd_systtools.fcl
Bumping this comment as part of review 2. This fcl could be about 4 lines long I think. Your other fcls do this nicely. In fact looking more closely, this fcl doesn't even run systtools? What is the point of it?

2024-02-14 16:48 UTC, henrylay97 commented on sbndcode/JobConfigurations/standard/caf/cafmakerjob_sbnd_sce.fcl
> +#include "eventweight_genie_systtools.fcl"
This should be in `cafmakerjob_sbnd.fcl` otherwise the relevant calls in fcls that inherit from that fcl won't work...

2024-02-14 16:48 UTC, henrylay97 commented on sbndcode/JobConfigurations/standard/caf/cafmakerjob_sbnd_sce.fcl
> +
As with this...

2024-02-14 16:48 UTC, henrylay97 commented on sbndcode/JobConfigurations/standard/caf/cafmakerjob_sbnd.fcl
> +   # Includes: pandoraTrackMCS, pandoraTrackRange, rns, systtools, fluxweight
This producer hasn't been defined in this fcl?

See below comments on `cafmakerjob_sbnd_sce.fcl`

2024-02-14 16:48 UTC, henrylay97 commented on sbndcode/JobConfigurations/standard/caf/cafmakerjob_sbnd.fcl
> +physics.producers.cafmaker.SystWeightLabels: ["systtools"]
Don't think we want to do this? It hasn't run this producer so it won't find these products?

2024-02-14 16:48 UTC, henrylay97 commented on sbndcode/JobConfigurations/standard/caf/cafmakerjob_sbnd_geniewgt.fcl
> +physics.producers.cafmaker.SystWeightLabels: ["systtools"]
On this an other fcls, you're changing the name of `genieweight` to `systtools`, do you want to reflect this in the fcl titles?

2024-02-14 16:48 UTC, henrylay97 commented on sbndcode/JobConfigurations/standard/caf/cafmakerjob_sbnd_genie_and_fluxwgt.fcl
> +physics.runprod: [rns, systttools, fluxweight, @sequence::physics.runprod]
Typo

2024-02-19 17:27 UTC, henrylay97 requested changes
We're getting there now @afropapp13. Most of them are now functional. Final set of changes to ensure the function of the fcls reflects their names and vice versa. See comments below.

2024-02-19 17:27 UTC, henrylay97 commented on sbndcode/JobConfigurations/standard/caf/cafmakerjob_sbnd.fcl
> +# input art files
What is the rationale for deleting line 140?

Also I think the `# input art files` can go, it doesn't really refer to what comes next (not from you but might as well remove while we're here.

2024-02-19 17:27 UTC, henrylay97 commented on sbndcode/JobConfigurations/standard/caf/cafmakerjob_sbnd_geniewgt.fcl
> +physics.producers.cafmaker.SystWeightLabels: ["systtools"]
@afropapp13 re-pinging this, think the file name should reflect its function.

2024-02-19 17:27 UTC, henrylay97 commented on sbndcode/JobConfigurations/standard/caf/cafmakerjob_sbnd_3drift_sce_runfmatch_geniewgt.fcl
> +physics.producers.cafmaker.SystWeightLabels: ["systtools"]
Looks good, name of fcl file should reflect producer name change?

2024-02-19 17:27 UTC, henrylay97 commented on sbndcode/JobConfigurations/standard/caf/cafmakerjob_sbnd_fluxwgt.fcl
> +physics.producers.cafmaker.SystWeightLabels: ["systtools"]
Not your fault but it looks like the name of this fcl file implies it only runs fluxwgt... hence my suggestion would be...

```suggestion
physics.runprod: [rns, fluxweight, @sequence::physics.runprod]
physics.producers.cafmaker.SystWeightLabels: ["fluxweight"]
```

2024-02-19 17:27 UTC, henrylay97 commented on sbndcode/JobConfigurations/standard/caf/cafmakerjob_sbnd_genie_and_fluxwgt.fcl
All good, just need the file name change again.

2024-02-19 17:27 UTC, henrylay97 commented on sbndcode/JobConfigurations/standard/caf/cafmakerjob_sbnd_sce.fcl
> +            systtools, cafmaker ]
No, remove this. The fcl name says it doesn't run any weights, that's why genieweight / fluxwgt aren't in this one.

2024-02-19 17:27 UTC, henrylay97 commented on sbndcode/JobConfigurations/standard/caf/cafmakerjob_sbnd_sce_genie_and_fluxwgt.fcl
All good, just name change.

2024-02-20 16:23 UTC, jedori0228 commented
@afropapp13 @sjgardiner @henrylay97 `SystTools` directory should be common between ICARUS and SBND, because there we already have thrown universes in fcl. ICARUS has its own one (https://github.com/SBNSoftware/icaruscode/tree/develop/fcl/caf/SystTools), so we should move this to `sbncode`.

2024-02-21 18:04 UTC, jedori0228 commented
> Hi @jedori0228 fully fully agree with this! Afro's branch does _directly_ copy the `syst_params_*` fcl file therefore keeping the thrown weights, as a stop gap. But if someone's willing to do the correct thing and move this up to sbncode immediately that would be great.

@henrylay97 I created PRs (https://github.com/SBNSoftware/sbncode/pull/433 and https://github.com/SBNSoftware/icaruscode/pull/697) where I moved Systtools directory from icaruscode and sbncode.

2024-02-21 19:21 UTC, fjnicolas commented
@jedori0228 thanks for the fast implmentation in `sbncode`. @afropapp13 @sjgardiner can you modify this branch accordingly??

2024-02-23 10:45 UTC, henrylay97 commented
I'm happy to do this later today if that's okay with @afropapp13 @sjgardiner?

2024-02-23 18:31 UTC, henrylay97 commented
This PR can now be closed. It is replaced by #417.

2024-02-23 18:31 UTC, closed without merging