Added OpFlashes and XARAPuCA flashes to SimpleFlash
SBNSoftware/sbndcode pull request #381
Opened 2023-08-15 21:32 UTC by Robert-Darby

- Added OpFlashes to SimpleFlash for SBND and ICARUS
- Added XARAPUCA flashes to SimpleFlash for SBND
- Updated SRSlice to accoutn for new flashes in CAF

2023-08-15 21:50 UTC, Robert-Darby commented
Related PRs:
icaruscode: https://github.com/SBNSoftware/icaruscode/pull/621
sbndcode: https://github.com/SBNSoftware/sbndcode/pull/381
sbncode: https://github.com/SBNSoftware/sbncode/pull/382
sbnanaobj: https://github.com/SBNSoftware/sbnanaobj/pull/107

2023-08-22 17:29 UTC, ikatza commented on sbndcode/FlashMatch/flashmatch_sbnd.fcl
> +sbnd_simple_flashmatch_ara_sce.OpFlashProducer: ["opflashtpc0xarapuca", "opflashtpc1xarapuca"]
Typos here.

2023-08-22 17:30 UTC, ikatza commented on sbndcode/FlashMatch/flashmatch_sbnd.fcl
> +sbnd_simple_flashmatch_sce_sce.PandoraProducer: "pandoraSCE"
Typo?

2023-08-22 17:32 UTC, ikatza commented on sbndcode/JobConfigurations/base/reco_sbnd.fcl
> +  fmatchoparaSCE:           @local::sbnd_simple_flashmatch_opara_sce
Review indentation of second column

2023-08-22 17:37 UTC, ikatza requested changes
Typos

2023-09-18 21:20 UTC, Robert-Darby commented
New metrics file for SBND: /sbnd/data/users/rdarby/flashmatch/opflash/nonlin/all_flash/FlashMatch/

2023-09-26 17:36 UTC, fjnicolas commented
Thanks @Robert-Darby, I will work on the `sbnd_data` update tomorrow

2023-09-27 15:23 UTC, ikatza commented
Looking at those metrics there's an oddity with the ratio metric for PMTs. The ratio should be equal or less than 1, but looking at the TH2 for simple flash and opflash it's clear that the ratio can take values higher than 1.

For now I suggest to postpone the investigation of the oddity, but update the upper limit of the histogram so that all data points get considered. In `flashmatch_sbnd.fcl` change `ratio.up` to 1.5 (maybe 2?)

New metrics need to be created.

2023-09-27 15:25 UTC, ikatza commented
> Thanks @Robert-Darby, I will work on the `sbnd_data` update tomorrow

It's still too early for that.

2023-09-27 15:58 UTC, fjnicolas commented
@ikatza the pmt detection efficiencies were updated some months ago. The efficiency for each flavour of PMT is now different (we were using a global efficiency of 3% for both coated/uncoated), meaning that the ratio metric is no longer constrained to [0, 1]. The flash matching metrics were updated accordingly in `sbnd_data`.

```
  # Detection efficiencies
  PMTCoatedVUVEff:       0.12       #PMT coated detection efficiency for direct (VUV) light
  PMTCoatedVISEff:       0.13       #PMT coated detection efficiency for reflected (VIS) light
  PMTUncoatedEff:        0.19       #PMT uncoated detection efficiency
```

@Robert-Darby @ikatza let me know when we are ready to update the metric files.

2023-10-10 16:30 UTC, ikatza approved these changes

2024-01-10 16:34 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/21398&builds=)

2024-01-10 16:34 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for e26:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/21399&builds=)

2024-01-10 16:46 UTC, FNALbuild commented
:x: CI build for SBND Failed at phase unit_test SBND on slf7 for c14:prof - ignored warnings for build -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/13299&builds=)

:rotating_light: For more details about the failed phase, check the [unit_test SBND phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/13299&platform=Linux%203.10.0-1160.102.1.el7.x86_64&phase=unit_test&buildtype=slf7%20c14:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/21398&builds=)

2024-01-10 16:49 UTC, FNALbuild commented
:x: CI build for SBND Failed at phase unit_test SBND on slf7 for e26:prof - ignored warnings for build -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/13300&builds=)

:rotating_light: For more details about the failed phase, check the [unit_test SBND phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/13300&platform=Linux%203.10.0-1160.102.1.el7.x86_64&phase=unit_test&buildtype=slf7%20e26:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/21399&builds=)

2024-01-10 17:14 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for e26:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/21400&builds=)

2024-01-10 17:14 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/21401&builds=)

2024-01-10 17:26 UTC, FNALbuild commented
:x: CI build for SBND Failed at phase unit_test SBND on slf7 for c14:prof - ignored warnings for build -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/13302&builds=)

:rotating_light: For more details about the failed phase, check the [unit_test SBND phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/13302&platform=Linux%203.10.0-1160.102.1.el7.x86_64&phase=unit_test&buildtype=slf7%20c14:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/21401&builds=)

2024-01-10 17:30 UTC, FNALbuild commented
:x: CI build for SBND Failed at phase unit_test SBND on slf7 for e26:prof - ignored warnings for build -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/13301&builds=)

:rotating_light: For more details about the failed phase, check the [unit_test SBND phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/13301&platform=Linux%203.10.0-1160.102.1.el7.x86_64&phase=unit_test&buildtype=slf7%20e26:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/21400&builds=)

2024-01-10 17:36 UTC, fjnicolas commented
trigger build SBNSoftware/sbndcode#395 SBNSoftware/sbncode#382 SBNSoftware/sbnanaobj#107

2024-01-10 17:40 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/21402&builds=)

2024-01-10 17:40 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for e26:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/21403&builds=)

2024-01-10 19:08 UTC, fjnicolas commented
Hi @Robert-Darby, I see in the CI that the `fmatch` is not filled as it used to be, e.g.,
```
338: Checking record 0
339:   rec.slc[0].fmatch.chargeCenter.x differs: 45.48662567138672 vs nan
340:   rec.slc[0].fmatch.chargeCenter.y differs: -2.4763777256011963 vs nan
341:   rec.slc[0].fmatch.chargeCenter.z differs: 258.91595458984375 vs nan
342:   rec.slc[0].fmatch.chargeQ differs: 1765561.5 vs nan
343:   rec.slc[0].fmatch.chargeWidth.x differs: 1.3069051504135132 vs nan
344:   rec.slc[0].fmatch.chargeWidth.y differs: 1.7959880828857422 vs nan
345:   rec.slc[0].fmatch.chargeWidth.z differs: 147.6423797607422 vs nan
```
is that expected?

2024-01-12 15:27 UTC, fjnicolas commented
trigger build SBNSoftware/sbncode#382 SBNSoftware/sbnanaobj#107

2024-01-12 15:30 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for e26:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/21425&builds=)

2024-01-12 15:30 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/21426&builds=)

2024-01-12 15:37 UTC, FNALbuild commented
:x: CI build for SBND Failed at phase build SBND on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/13319&builds=)

:rotating_light: For more details about the failed phase, check the [build SBND phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/13319&platform=Linux%203.10.0-1160.102.1.el7.x86_64&phase=build&buildtype=slf7%20c14:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/21426&builds=)

2024-01-12 15:38 UTC, FNALbuild commented
:x: CI build for SBND Failed at phase build SBND on slf7 for e26:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/13320&builds=)

:rotating_light: For more details about the failed phase, check the [build SBND phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/13320&platform=Linux%203.10.0-1160.102.1.el7.x86_64&phase=build&buildtype=slf7%20e26:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/21425&builds=)

2024-01-15 15:32 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/21444&builds=)

2024-01-15 16:01 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for e26:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/21443&builds=)

2024-01-15 16:20 UTC, FNALbuild commented
:x: CI build for SBND Failed at phase ci_tests SBND on slf7 for c14:prof - ignored warnings for build -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/13333&builds=)

:rotating_light: For more details about the failed phase, check the [ci_tests SBND phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/13333&platform=Linux%203.10.0-1160.102.1.el7.x86_64&phase=ci_tests&buildtype=slf7%20c14:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/21444&builds=)

2024-01-16 11:24 UTC, merged