SimChannel Module Label
SBNSoftware/sbndcode pull request #409
Opened 2024-02-01 15:43 UTC by henrylay97

This changes the module label used by the back tracker for SimChannels from `simdrift` (1D simulation) to `simtpc2d:simpleSC` (WireCell 2D simulation).

Details are in [docDB #33131](https://sbn-docdb.fnal.gov/cgi-bin/sso/ShowDocument?docid=33131).

Like with the interplane drift effect this invalidates the use of these fcls on 1D simulation files but I think given the lack of parallel workflows this is the best approach.

I change the base use of this in the definition of the backtracker service _plus_ other module label locations that are currently pointed at `simdrift`. @lynnt20 feel free to weigh in with a WireCell perspective.

2024-02-01 16:02 UTC, absolution1 approved these changes
Looks good, thanks @henrylay97

2024-02-01 16:21 UTC, lynnt20 approved these changes
thanks @henrylay97 :)

2024-02-15 09:00 UTC, fjnicolas commented
Thanks @henrylay97 for the bug fix (and #408 as well)! I would just update the README in `JobConfigurations` specifying the set of working fhicls to warn people the legacy 1D ones won't work as expected. If you don't mind, I can push directly to this branch before merging.

2024-02-15 09:25 UTC, henrylay97 commented
@fjnicolas that's a great shout yeah. I can do that later today and push to here if that fits timescale?

2024-02-15 09:30 UTC, fjnicolas commented
yep, no rush!

2024-02-15 18:36 UTC, henrylay97 commented
@fjnicolas done :)

2024-02-15 19:14 UTC, fjnicolas commented
trigger build

2024-02-15 19:18 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for e26:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/21838&builds=)

2024-02-15 19:18 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/21839&builds=)

2024-02-15 19:31 UTC, FNALbuild commented
:x: CI build for SBND Failed at phase unit_test SBND on slf7 for c14:prof - ignored warnings for build -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/13606&builds=)

:rotating_light: For more details about the failed phase, check the [unit_test SBND phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/13606&platform=Linux%203.10.0-1160.102.1.el7.x86_64&phase=unit_test&buildtype=slf7%20c14:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/21839&builds=)

2024-02-15 19:32 UTC, FNALbuild commented
:x: CI build for SBND Failed at phase unit_test SBND on slf7 for e26:prof - ignored warnings for build -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/13605&builds=)

:rotating_light: For more details about the failed phase, check the [unit_test SBND phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/13605&platform=Linux%203.10.0-1160.102.1.el7.x86_64&phase=unit_test&buildtype=slf7%20e26:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/21838&builds=)

2024-02-15 22:29 UTC, fjnicolas commented
The errors in the unit tests are more than expected since they are using the 1D workflow, I'm working with @RachelCoackley to get them up to date to work with WC

2024-02-15 22:31 UTC, lynnt20 commented on sbndcode/LArG4/mcreco_sbnd.fcl
> +sbnd_mcreco.SimChannelLabel: "simtpc2d:simpleSC"
Looks like this line is responsible for the CI test failures! `mcreco_sbnd.fcl` is used by `standard_g4_sbnd.fcl` to create `MCTrack` and `MCShower`. At the g4 stage, WireCell hasn't yet been run, and so the `SimChannel`s with label `simtpc2d:simpleSC` haven't yet been produced. 

The most straightforward solution (in terms of minimal code changes) that I can think of so far is to remove `mcreco` from the g4 stage, and add it at the end of the `wirecell_sim_sp_sbnd.fcl` stage. Not sure if this will really affect other CI tests or if it would cause other major changes 😓

2024-02-15 22:35 UTC, lynnt20 commented on sbndcode/LArG4/mcreco_sbnd.fcl
> +sbnd_mcreco.SimChannelLabel: "simtpc2d:simpleSC"
@fjnicolas whoops sorry didn't see your comment until after I wrote mine

2024-02-16 10:52 UTC, fjnicolas requested changes

2024-02-16 10:52 UTC, fjnicolas commented on sbndcode/JobConfigurations/standard/caf/cafmakerjob_sbnd.fcl
```suggestion
#include "services_sbnd.fcl"
#include "geometry_sbnd.fcl"
#include "simulationservices_sbnd.fcl"
```

2024-02-16 10:54 UTC, fjnicolas commented on sbndcode/JobConfigurations/standard/caf/cafmakerjob_sbnd.fcl
The fhicl dump check failed though, the SBND-specific BackTracker and ParticleInventory services are defined in `simulationservices_sbnd.fcl`

2024-02-16 11:22 UTC, henrylay97 commented on sbndcode/JobConfigurations/standard/caf/cafmakerjob_sbnd.fcl
For some reason it won't let me commit your suggestion. I'll try again in a bit.

2024-02-16 16:14 UTC, fjnicolas commented on sbndcode/JobConfigurations/standard/caf/cafmakerjob_sbnd.fcl
done!

2024-02-16 16:16 UTC, merged