Move bnb_common config fcl to sbncode
SBNSoftware/sbndcode pull request #415
Opened 2024-02-19 22:49 UTC by rodralva

Following the update of BNB flux files for HNL and other BSM models generation used in MeVPrtl, I'm moving the commong config file for the BNB flux to sbncode where ICARUS people can also use it. 
This PR depends on  [sbncode PR#432](https://github.com/SBNSoftware/sbncode/pull/432)

2024-02-19 23:09 UTC, VCLanNguyen approved these changes

2024-02-19 23:20 UTC, jicrespo requested changes
This file has SBND-only information (coordinates, dimensions, angles) that is not useful to ICARUS. I would keep it in `sbndcode` or in a separate file `bnb_kaon_sbnd.fcl` in `sbncode`. The `bnb_kaon` block may be moved.

2024-02-20 02:00 UTC, rodralva commented
separated workflow in 2 files as @jicrespo suggested, now sbndcode points towards sbnd-specific file

2024-02-20 02:01 UTC, rodralva commented
> This file has SBND-only information (coordinates, dimensions, angles) that is not useful to ICARUS. I would keep it in `sbndcode` or in a separate file `bnb_kaon_sbnd.fcl` in `sbncode`. The `bnb_kaon` block may be moved.

separated workflow in 2 files as @jicrespo suggested, now sbndcode points towards sbnd-specific file

2024-02-26 12:00 UTC, merged