Adding CRT and PDS info in calib ntuple
SBNSoftware/sbndcode pull request #422
Opened 2024-02-29 02:42 UTC by sungbinoh

Notes
- reco2_sce.fcl is updated to include results from additional analysis modules (CRTCalibAna and SBNDFlashAssAna) into the calibration ntuple.
- CRTCalibAna is based on Henry's CRTAnalysis module and ICARUS's calibration ntuple structure. CRTCalibAna has Henry's tree in it for just in case. If we are sure about variable selections for CRT in the calibration nutple, we might select them and remove Henry's tree from the calibration ntuple.
- SBNDFlashAssAna is exactly same with ICARUS's analysis module (https://github.com/SBNSoftware/icaruscode/blob/develop/icaruscode/PMT/OpReco/ICARUSFlashAssAna_module.cc) that adds PMT information into calibration ntuple.

Discussions
1. I added "PDS" directory for SBNDFlashAssAna module. If someone wants to rearrange it, please feel free to do so. (For Linyan and Mike, calibration ntuples that I produced using Grid to test the workflow still have "PMT" for variable names..)
2. Modified "PMT" into "PDS" inside SBNDFlashAssAna where the original file from ICARUS has PMT since PMTs are only light detector of the ICARUS detector.
3. I added several Iines in reco2_sce.fcl forCRTCalibAna and SBNDFlashAssAna . If someone wants to include those lines in reco_sbnd.fcl, please feel free to do so.
4. The `TriggerLabel: "generator"` in reco2_sce.fcl did not work during my test for workflow since there was no trigger information  in the codes that are compatible with 2023B. If we have them for the new production, please modify this line with correct TriggerLabel name.

2024-02-29 17:43 UTC, VCLanNguyen commented on sbndcode/JobConfigurations/standard/reco/reco2_sce.fcl
Hi @sungbinoh, I think it's better to declare all the producer and analyzer module in reco_sbnd.fcl
Example here:
https://github.com/SBNSoftware/sbndcode/blob/develop/sbndcode/JobConfigurations/base/reco_sbnd.fcl#L244-L250

And then inherit the module in the reco2 fcl. 
With this setup, both reco2_sce and non-sce can inherit the new modules.

2024-02-29 17:58 UTC, VCLanNguyen commented
On point 4:
- I don't think SBND workflow currently simulates trigger information so there's no trigger info in the code at all.
- Therefore, I don't know what trigger products SBND will use in the future, it might or might not be the following two products since SBND does not share the same hardware trigger as ICARUS.
```
#include "lardataobj/RawData/TriggerData.h"
#include "sbnobj/Common/Trigger/ExtraTriggerInfo.h"
```

2024-03-01 17:00 UTC, fjnicolas commented
@sungbinoh there are already some PDS related directories (`OpDetSim`, `OpDetReco` and `OpDetAnalyzer`), I'd probably move the PDS analyzer to `OpDetAnalyzer`

2024-03-11 14:15 UTC, linyan-w commented
> @sungbinoh there are already some PDS related directories (`OpDetSim`, `OpDetReco` and `OpDetAnalyzer`), I'd probably move the PDS analyzer to `OpDetAnalyzer`

The PDS analyzer in this version is dedicated to calibration, and will be further trimmed down in later development. That's different from the PDS analyzer and we'd like to keep them separate, just like the TPC analyzer and the TPC calibration part is separate.

2024-03-11 14:34 UTC, fjnicolas commented
> > @sungbinoh there are already some PDS related directories (`OpDetSim`, `OpDetReco` and `OpDetAnalyzer`), I'd probably move the PDS analyzer to `OpDetAnalyzer`
> 
> The PDS analyzer in this version is dedicated to calibration, and will be further trimmed down in later development. That's different from the PDS analyzer and we'd like to keep them separate, just like the TPC analyzer and the TPC calibration part is separate.

@linyan-w  Can we have then a common parent directory (e.g. `Calibration`) for all the calibration related analyzers?  We can make then subdirectories for each subsystem (e.g. CRT, PDS...) with all these dedicated analyzers devoted exclusively to detector calibration. As it is right now, we have CRT calibration related analyzers in `CRT/CRTAna` and PDS ones in `PDS/OpReco` (and that's definitely not PDS reconstruction, but analysis)

2024-03-11 14:45 UTC, linyan-w commented
> > > @sungbinoh there are already some PDS related directories (`OpDetSim`, `OpDetReco` and `OpDetAnalyzer`), I'd probably move the PDS analyzer to `OpDetAnalyzer`
> > 
> > 
> > The PDS analyzer in this version is dedicated to calibration, and will be further trimmed down in later development. That's different from the PDS analyzer and we'd like to keep them separate, just like the TPC analyzer and the TPC calibration part is separate.
> 
> @linyan-w Can we have then a common parent directory (e.g. `Calibration`) for all the calibration related analyzers? We can make then subdirectories for each subsystem (e.g. CRT, PDS...) with all these dedicated analyzers devoted exclusively to detector calibration. As it is right now, we have CRT calibration related analyzers in `CRT/CRTAna` and PDS ones in `PDS/OpReco` (and that's definitely not PDS reconstruction, but analysis)

That's a good idea. I'm not sure we want to do so in the non-empty Calibration directory. Let me have a look at the existing modules there.

2024-03-12 01:52 UTC, linyan-w commented on sbndcode/JobConfigurations/standard/reco/reco2_sce.fcl
The fcl files are updated according to the suggestion. I tested with a small sample and everything still seems to work. Could you please have a look? Thanks Lan.

2024-03-12 15:03 UTC, VCLanNguyen commented on sbndcode/JobConfigurations/standard/reco/reco2_sce.fcl
> +services.DetectorClocksService: @local::sbnd_detectorclocks
This line is not the service block in reco_sbnd.fcl so you can declare it there and remove this line in reco2_sce.fcl

2024-03-12 15:03 UTC, VCLanNguyen commented on sbndcode/JobConfigurations/base/reco_sbnd.fcl
> +# caloskimana: [ caloskim, pmtskim ]
if this is not needed, you can remove this line as well.

2024-03-12 15:03 UTC, VCLanNguyen commented on sbndcode/JobConfigurations/base/reco_sbnd.fcl
> +    	CRTBackTrackerAlg: @local::crtbacktrackeralg_sbnd
Is it possible to write a fcl like pmt_skim i.e. crt_skim.fcl and inherit a table i.e. local::crtskim_sbnd
Just so for future you can always edit crt_skim.fcl without the need to touch reco_sbnd.fcl

2024-03-12 15:04 UTC, VCLanNguyen commented on sbndcode/JobConfigurations/standard/reco/reco2_sce.fcl
> +services.DetectorClocksService: @local::sbnd_detectorclocks
This line is not the service block in reco_sbnd.fcl so you can declare it there and remove this line in reco2_sce.fcl

2024-03-12 15:06 UTC, VCLanNguyen commented on sbndcode/JobConfigurations/standard/reco/reco2_sce.fcl
Hi @linyan-w , I add some more comments mostly for tidying up. Otherwise looks good to me.

2024-03-12 15:08 UTC, VCLanNguyen commented on sbndcode/JobConfigurations/base/reco_sbnd.fcl
> +caloskimana: [ caloskim, crtskim, pmtskim ]
for clarity sake, you can rename `caloskimana` to `calibskimana` or something like that :P

2024-03-12 15:28 UTC, linyan-w commented on sbndcode/JobConfigurations/standard/reco/reco2_sce.fcl
> +##include "crtbacktrackeralg_sbnd.fcl"
> These two lines are already declared in reco_sbnd.fcl so no need to include them here

Thanks, Lan! I tidied up the commented lines I introduced while testing. I agree that we should have a crt_skim.fcl but I'd defer that to the future as we're rushing into the next production. The same applies to the other comments.

2024-03-12 16:01 UTC, fjnicolas commented
@linyan-w the `Calibration` directory is now empy, in case you want to move the analyzers/skimmer fhicl configurations there. If not for this PR, can we at least move the `SBNDFlashAssAna` to the `OpDetAnalyzer` directory so we avoid having duplicated/unnecesarry directories for the light detection system code? Thank you!

2024-03-12 17:37 UTC, fjnicolas commented
@VCLanNguyen happy with the last changes?

2024-03-12 17:45 UTC, VCLanNguyen commented
> @VCLanNguyen happy with the last changes?

@linyan-w misses deleting some lines regarding services in reco2_sce.fcl and move detector clock service from reco2_sce.fcl to reco_sbnd.fcl. 
Should be a quick edit then good to go.

2024-03-12 18:01 UTC, linyan-w commented
> > @VCLanNguyen happy with the last changes?
> 
> @linyan-w misses deleting some lines regarding services in reco2_sce.fcl and move detector clock service from reco2_sce.fcl to reco_sbnd.fcl. Should be a quick edit then good to go.


How about now?

2024-03-12 18:09 UTC, VCLanNguyen commented
> > > @VCLanNguyen happy with the last changes?
> > 
> > 
> > @linyan-w misses deleting some lines regarding services in reco2_sce.fcl and move detector clock service from reco2_sce.fcl to reco_sbnd.fcl. Should be a quick edit then good to go.
> 
> How about now?

Can you completely delete

2024-03-12 18:14 UTC, VCLanNguyen requested changes

2024-03-12 18:14 UTC, VCLanNguyen commented on sbndcode/JobConfigurations/standard/reco/reco2_sce.fcl
> +#include "simulationservices_sbnd.fcl"
```suggestion
```

2024-03-12 18:14 UTC, VCLanNguyen commented on sbndcode/JobConfigurations/standard/reco/reco2_sce.fcl
> +services.DetectorClocksService: @local::sbnd_detectorclocks
```suggestion
```

2024-03-12 18:21 UTC, VCLanNguyen commented
All look good to me.

2024-03-12 18:22 UTC, fjnicolas commented
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_85_00

2024-03-12 18:23 UTC, VCLanNguyen commented
> On point 4:
> 
>     * I don't think SBND workflow currently simulates trigger information so there's no trigger info in the code at all.
> 
>     * Therefore, I don't know what trigger products SBND will use in the future, it might or might not be the following two products since SBND does not share the same hardware trigger as ICARUS.
> 
> 
> ```
> #include "lardataobj/RawData/TriggerData.h"
> #include "sbnobj/Common/Trigger/ExtraTriggerInfo.h"
> ```

@linyan-w I would open an issue about the pmt skim module does not work with trigger product right now since it's not available on SBND. Just so we can keep track of it in the future.

2024-03-12 18:35 UTC, linyan-w commented
> thank you @sungbinoh @linyan-w !

Thanks for the help Lan and Fran!

2024-03-12 18:37 UTC, linyan-w commented
> > On point 4:
> > ```
> > * I don't think SBND workflow currently simulates trigger information so there's no trigger info in the code at all.
> > 
> > * Therefore, I don't know what trigger products SBND will use in the future, it might or might not be the following two products since SBND does not share the same hardware trigger as ICARUS.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > #include "lardataobj/RawData/TriggerData.h"
> > #include "sbnobj/Common/Trigger/ExtraTriggerInfo.h"
> > ```
> 
> @linyan-w I would open an issue about the pmt skim module does not work with trigger product right now since it's not available on SBND. Just so we can keep track of it in the future.

We have multiple items for improvement on this ntuple as we deferred several suggestions and found several issues already. I currently have these in a slack chat with Sungbin. If the nominal workflow is to document them in issues, then sure I can open one.

2024-03-12 18:45 UTC, VCLanNguyen commented
> > > On point 4:
> > > ```
> > > * I don't think SBND workflow currently simulates trigger information so there's no trigger info in the code at all.
> > > 
> > > * Therefore, I don't know what trigger products SBND will use in the future, it might or might not be the following two products since SBND does not share the same hardware trigger as ICARUS.
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ```
> > > #include "lardataobj/RawData/TriggerData.h"
> > > #include "sbnobj/Common/Trigger/ExtraTriggerInfo.h"
> > > ```
> > 
> > 
> > @linyan-w I would open an issue about the pmt skim module does not work with trigger product right now since it's not available on SBND. Just so we can keep track of it in the future.
> 
> We have multiple items for improvement on this ntuple as we deferred several suggestions and found several issues already. I currently have these in a slack chat with Sungbin. If the nominal workflow is to document them in issues, then sure I can open one.

I think opening an Issue + Improvement would be good for tracking and good practice!  Thanks!

2024-03-12 18:50 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/22123&builds=)

2024-03-12 18:55 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for e26:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/22124&builds=)

2024-03-12 18:57 UTC, linyan-w commented
> > > > On point 4:
> > > > ```
> > > > * I don't think SBND workflow currently simulates trigger information so there's no trigger info in the code at all.
> > > > 
> > > > * Therefore, I don't know what trigger products SBND will use in the future, it might or might not be the following two products since SBND does not share the same hardware trigger as ICARUS.
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > ```
> > > > #include "lardataobj/RawData/TriggerData.h"
> > > > #include "sbnobj/Common/Trigger/ExtraTriggerInfo.h"
> > > > ```
> > > 
> > > 
> > > @linyan-w I would open an issue about the pmt skim module does not work with trigger product right now since it's not available on SBND. Just so we can keep track of it in the future.
> > 
> > 
> > We have multiple items for improvement on this ntuple as we deferred several suggestions and found several issues already. I currently have these in a slack chat with Sungbin. If the nominal workflow is to document them in issues, then sure I can open one.
> 
> I think opening an Issue + Improvement would be good for tracking and good practice! Thanks!

OK, I'm opening an issue here:
https://github.com/SBNSoftware/sbndcode/issues/427
Will assign it to Sungbin and others (hopefully I can find someone in PDS/CRT groups who can help with the trimming).

2024-03-12 19:11 UTC, FNALbuild commented
:x: CI build for SBND Failed at phase unit_test SBND on slf7 for c14:prof - ignored warnings for build -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/13823&builds=)

:rotating_light: For more details about the failed phase, check the [unit_test SBND phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/13823&platform=Linux%203.10.0-1160.105.1.el7.x86_64&phase=unit_test&buildtype=slf7%20c14:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/22123&builds=)

2024-03-12 19:37 UTC, FNALbuild commented
:warning: CI build for SBND Warning at phase ci_tests SBND on slf7 for e26:prof - ignored warnings for build -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/13824&builds=)

:rotating_light: For more details about the warning phase, check the [ci_tests SBND phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/13824&platform=Linux%203.10.0-1160.105.1.el7.x86_64&phase=ci_tests&buildtype=slf7%20e26:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/22124&builds=)

2024-03-13 09:17 UTC, fjnicolas commented
> > > On point 4:
> > > ```
> > > * I don't think SBND workflow currently simulates trigger information so there's no trigger info in the code at all.
> > > 
> > > * Therefore, I don't know what trigger products SBND will use in the future, it might or might not be the following two products since SBND does not share the same hardware trigger as ICARUS.
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ```
> > > #include "lardataobj/RawData/TriggerData.h"
> > > #include "sbnobj/Common/Trigger/ExtraTriggerInfo.h"
> > > ```
> > 
> > 
> > @linyan-w I would open an issue about the pmt skim module does not work with trigger product right now since it's not available on SBND. Just so we can keep track of it in the future.
> 
> We have multiple items for improvement on this ntuple as we deferred several suggestions and found several issues already. I currently have these in a slack chat with Sungbin. If the nominal workflow is to document them in issues, then sure I can open one.

Yes, opnening a issue is the best practice, thanks @linyan-w! All the CI tests passed, PR ready to merge in the next release.

2024-03-22 13:56 UTC, merged