Feature/afilkins commissioning trees
SBNSoftware/sbndcode pull request #436
Opened 2024-03-20 15:04 UTC by flaviacicala

This PR includes:

- a new CRT reconstruction using sbn**d**::crt::CRTTrack, instead of the default sbn::crt::crtTrack. The latter creates a track out of every possible pair of two crt hits, while the new CRT reconstruction, developed by @henrylay97, has more reasonable criteria for forming tracks which consists of looking at the timing, and includes the possibility of a track with 2 or 3 points along it which accommodates the case of crossing both of the top CRTs and one other wall.
- HitDumper module now uses these new SBND tracks instead of the standard SBN ones. This includes switching over from using sbn::crt::CRTHit to using sbnd::crt::CRTSpacePoint. This was implemented by Amy Filkins.

2024-03-20 15:16 UTC, fjnicolas commented
Hi @flaviacicala, thanks for the PR.
- What's the timeline for this PR to get in? i.e. do you need this for the production release?
- Also, can you rebase this PR? `develop` has diverged too much from `v09_72_01`, so the integration can be really difficult...
Thanks!

2024-03-20 15:22 UTC, flaviacicala commented
Hi Fran, when is the next production release? Rather than needing this in for a specific time, the commissioning team would like this to become the default process to make CRT tracks to fix some known artificial features seen on our side. What is a reasonable timeline to achieve this from your side?

I agree that a rebase is needed. I'll do that now.

2024-03-22 10:22 UTC, henrylay97 commented
Hi @flaviacicala really glad this is going in, thank you! Any luck on a rebase / develop merge? Happy to review once that's done and is easier to parse :D

2024-03-22 15:44 UTC, fjnicolas commented
thanks @flaviacicala for the last commit! @henrylay97 @marcodeltutto this is ready for review

2024-03-22 16:17 UTC, fjnicolas requested changes
@flaviacicala I left some requests that we'll need to integrate this with `develop` branch. I'll leave Marco/Henry comment on the HitDumper/CRT changes, but looks good to me overall.

2024-03-22 16:17 UTC, fjnicolas commented on sbndcode/CRT/CRTBackTracker/CMakeLists.txt
> +                        sbnobj_SBND_CRT
the library is `sbnobj::SBND_CRT`, we need to leave the namespace notation
```suggestion
                        sbnobj::SBND_CRT
```

2024-03-22 16:17 UTC, fjnicolas commented on sbndcode/CRT/CRTReco/CMakeLists.txt
> +                        sbnobj_SBND_CRT
Same:
```suggestion
                        sbnobj::SBND_CRT
```

2024-03-22 16:17 UTC, fjnicolas commented on sbndcode/Commissioning/fcls/run_muontrack_test.fcl
> +#include "caldata_sbnd.fcl"
not needed?
```suggestion
```

2024-03-22 16:17 UTC, fjnicolas commented on sbndcode/Commissioning/fcls/run_muontrack_test.fcl
> +#include "vertexfindermodules.fcl"
these are not needed. We minimumly need to remove `#include "cluster_sbnd.fcl"`, otherwise we'll have a conflict when merging #421 

```suggestion
```

2024-03-26 10:01 UTC, henrylay97 requested changes
Hi @flaviacicala this is great thanks so much for doing this. I agree with the requests made by Fran for smooth integration. I also have some comments of my own. Most are aesthetic changes that occured in my branch during the review stage, and therefore weren't inherited here, very quick fixes. The slightly more substantial ones are in `HitDumper` itself where I think we can make slightly fuller use of the information available from the reconstruction to save analyzers time & effort.

Thanks! :smile:

2024-03-26 11:30 UTC, flaviacicala commented on sbndcode/Commissioning/HitDumper_module.cc
> +      //_chit_plane[i] = ip; //This doesn't seem to exist
@henrylay97, is this something you could implement?

2024-03-26 17:20 UTC, marcodeltutto requested changes
Thanks @flaviacicala! Looks good to me. Just a minor comment.

2024-03-26 17:20 UTC, marcodeltutto commented on sbndcode/CRT/CRTBackTracker/CMakeLists.txt
> +                 LIBRARY_NAME sbndcode_CRT_CRTBackTracker
Unless there's a specific reason, I would remove this line as the library name is automatically assigned.

2024-03-26 17:20 UTC, marcodeltutto commented on sbndcode/CRT/CRTReco/CMakeLists.txt
> +                 LIBRARY_NAME sbndcode_CRT_CRTReco
Same

2024-03-26 17:20 UTC, marcodeltutto commented on sbndcode/CRT/CRTSimulation/CMakeLists.txt
> +                 LIBRARY_NAME sbndcode_CRT_CRTSimulation
Same

2024-03-26 17:20 UTC, marcodeltutto commented on sbndcode/CRT/CRTTPCMatching/CMakeLists.txt
> +                 LIBRARY_NAME sbndcode_CRT_CRTTPCMatching
Same

2024-03-28 10:59 UTC, fjnicolas approved these changes

2024-03-28 11:04 UTC, fjnicolas commented
@henrylay97 @flaviacicala where do things stand for the two unresolved comments? Do you prefer more time to implement it or merging this in as it is right now? Thanks!

2024-03-28 11:06 UTC, flaviacicala commented
> @henrylay97 @flaviacicala where do things stand for the two unresolved comments? Do you prefer more time to implement it or merging this in as it is right now? Thanks!

I would merge this now to be sure that it actually goes in. We can make a new PR when the things we want to implement are done. What do you say @henrylay97 ?

2024-03-28 11:10 UTC, henrylay97 approved these changes
Sorry I've been really snowed with :writing_hand: 

@fjnicolas how imminent is the next release?

If it isn't super imminent then let me see if I can find time to implement something for those two points in the next couple of days, both are pretty straightforward and would be useful to analysers imo. If I haven't found time when you're ready to cut a release then this can go in and I'll prepare a separate branch!

2024-03-28 11:24 UTC, fjnicolas commented
> Sorry I've been really snowed with ✍️
> 
> @fjnicolas how imminent is the next release?
> 

I actuallly have `v09_87_00` ready to go but a bug was foud in the ROOT version used by that tag, so I'll probably skip this one... So, I don't think next Monday (LArSoft published a patch fix yesterday, and it now needs to be propagated first to sbncode and then to SBND...).

> If it isn't super imminent then let me see if I can find time to implement something for those two points in the next couple of days, both are pretty straightforward and would be useful to analysers imo. If I haven't found time when you're ready to cut a release then this can go in and I'll prepare a separate branch!

That sounds good! I'll make a last minute merge then.

2024-03-28 11:26 UTC, fjnicolas commented
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_87_00

2024-03-28 11:49 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/22302&builds=)

2024-03-28 11:55 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for e26:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/22303&builds=)

2024-03-28 12:16 UTC, FNALbuild commented
:x: CI build for SBND Failed at phase build SBND on slf7 for e26:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/13942&builds=)

:rotating_light: For more details about the failed phase, check the [build SBND phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/13942&platform=Linux%203.10.0-1160.105.1.el7.x86_64&phase=build&buildtype=slf7%20e26:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/22303&builds=)

2024-03-28 12:18 UTC, FNALbuild commented
:x: CI build for SBND Failed at phase build SBND on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/13941&builds=)

:rotating_light: For more details about the failed phase, check the [build SBND phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/13941&platform=Linux%203.10.0-1160.105.1.el7.x86_64&phase=build&buildtype=slf7%20c14:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/22302&builds=)

2024-03-28 12:37 UTC, marcodeltutto approved these changes

2024-04-01 09:36 UTC, henrylay97 commented
Hi folks @flaviacicala @fjnicolas 

Took a brief look over the weekend at filling the extra fields as promised. This branch, however, doesn't compile, as is clear from the CI tests too. I was able to quickly hack together a version that does compile & then I ran into fcl issues with the workflow, if you run the commissioning fcls you seem to be missing products that are needed when hit dumper gets run in reco1.

This concerns me a little that this branch is clearly not what has been being run in the offline. Relatively easy to get it to compile but could do with some input on what the workflow plans are from experts?

2024-04-02 08:07 UTC, fjnicolas commented
> Hi folks @flaviacicala @fjnicolas
> 
> Took a brief look over the weekend at filling the extra fields as promised. This branch, however, doesn't compile, as is clear from the CI tests too. I was able to quickly hack together a version that does compile & then I ran into fcl issues with the workflow, if you run the commissioning fcls you seem to be missing products that are needed when hit dumper gets run in reco1.
> 
> This concerns me a little that this branch is clearly not what has been being run in the offline. Relatively easy to get it to compile but could do with some input on what the workflow plans are from experts?

Hi @henrylay97 thanks for having a look! Probably all the CRT related hit producers need to be defined in `run_hitdumper.fcl`? In a similar wat yo `fasthit` ot `ophitpmt`... @flaviacicala can you confirm what were you running offline?

2024-05-20 23:04 UTC, bear-is-asleep commented
> Hi Bear! There is work going on offline to reproduce the intention of this branch. We'll get something to you as soon as we can! Beth McCusker is the main developer with help from me and Flavia.

Thanks! Just checking in since I recently took over release manager duties.

2024-06-04 16:32 UTC, bear-is-asleep commented
Closing upon the @henrylay97 request. To be superseded by [PR 475](https://github.com/SBNSoftware/sbndcode/pull/475)

2024-06-04 16:32 UTC, closed without merging