Feature/bethanym hit dumper pr
SBNSoftware/sbndcode pull request #475
Opened 2024-05-30 09:40 UTC by bethmccusker

-  HitDumper module now uses the new CRT clustering reconstruction workflow
- CRT specific parts of HitDumper module have been tidied up significantly and many variable names have been changed to more sensible ones, along with additional CRT track variables being added. 
-  This PR supersedes #436 - same goal, new implementation
- Addition of a fcl (reco1_sce_comm_muontrack_no_cluster3d.fcl)
- Addition of a new muon hit plane variable (mhit_plane) that was also in PR #436

2024-05-30 16:00 UTC, bear-is-asleep requested changes
I'm very happy these changes are being made! I made a few requests on the fcls before I can approve. I also left a few suggestions such as printing which module label can't be found, since it helps for debugging.

2024-06-05 01:33 UTC, henrylay97 commented on sbndcode/Commissioning/fcls/hitdumpermodule.fcl
> +    readpmtTrigger:           false
A fair comment. Although at this stage of commissioning (and probably for a lot longer) exactly what is available in each data/simulated sample is changing very rapidly so custom fcls are going to be ubiquitous I think.

2024-06-05 01:35 UTC, henrylay97 commented on sbndcode/Commissioning/fcls/reco1_sce_comm_muontrack_no_cluster3d.fcl
A very fair point on the first one @bethmccusker does that make sense to you?

Although on the latter I'd disagree, its a broad description to describe the stage. Same is true in other stages, we don't change the process name for subtle differences.

2024-06-05 01:36 UTC, henrylay97 commented on sbndcode/Commissioning/fcls/run_muontrack.fcl
I think in the majority of scenarios we will actually want both?

But yeah @bethmccusker could make two versions :)

2024-06-05 01:37 UTC, henrylay97 commented on sbndcode/Commissioning/HitDumper_module.cc
> +    std::cout << "Failed to get sbnd::crt::CRTStripHit data product." << std::endl;
Agreed

2024-06-06 09:56 UTC, flaviacicala commented on sbndcode/Commissioning/fcls/hitdumpermodule.fcl
> +    readpmtTrigger:           false
Would it be preferable to make a copy of hitdumpermodule.fcl with these specific changes in it? That way we would preserve the "original" fcl, but still store the custom one used for this production.

2024-06-06 09:56 UTC, flaviacicala commented on sbndcode/Commissioning/fcls/reco1_sce_comm_muontrack_no_cluster3d.fcl
I would agree with Henry

2024-06-06 15:23 UTC, bear-is-asleep commented on sbndcode/Commissioning/fcls/hitdumpermodule.fcl
> +    readpmtTrigger:           false
You could just make a seperate config within the same fcl file. Something like this https://github.com/SBNSoftware/sbndcode/blob/b844be7166ba2fce3aa14d576086188b43e9c003/sbndcode/Commissioning/fcls/hitdumpermodule.fcl#L51-L53

2024-06-06 15:23 UTC, bear-is-asleep commented on sbndcode/Commissioning/fcls/reco1_sce_comm_muontrack_no_cluster3d.fcl
Fair enough on the second point. But we should do the first point for sure

2024-06-18 21:36 UTC, henrylay97 requested changes
Hi Beth, a few more comments here. Have a look at them and we can chat about them offline :)

2024-06-18 21:36 UTC, henrylay97 commented on sbndcode/Commissioning/HitDumper_module.cc
> +    std::cout << "Failed to get sbnd::crt::CRTStripHit data product (fCRTStripHitModuleLabel)." << std::endl;
This will just print the word "fCRTStripHitModuleLabel" not the value of the object.

```suggestion
    std::cout << "Failed to get sbnd::crt::CRTStripHit data product ( " << fCRTStripHitModuleLabel << ")." << std::endl;
```

2024-06-18 21:36 UTC, henrylay97 commented on sbndcode/Commissioning/HitDumper_module.cc
> +      std::cout << "Failed to get sbnd::crt::CRTSpacePoint data product (CRTSpacePointModuleLabel)." << std::endl;
Same again

2024-06-18 21:36 UTC, henrylay97 commented on sbndcode/Commissioning/HitDumper_module.cc
> +      std::cout << "Failed to get sbnd::crt::CRTTrack data product (CRTTrackModuleLabel)." << std::endl;
Same again

2024-06-18 21:36 UTC, henrylay97 commented on sbndcode/Commissioning/fcls/hitdumpermodule.fcl
> + hitdumper_data.readTruth: false
What's going on here? At minimum this is a typo?

2024-06-18 21:36 UTC, henrylay97 commented on sbndcode/Commissioning/fcls/hitdumpermodule.fcl
> + hitdumper_data.readTruth: false
And you haven't changed the defaults here. The idea was to make sure the standard defaults are the same as before :) and then update them in your run fcl.

2024-06-18 21:36 UTC, henrylay97 commented on sbndcode/Commissioning/fcls/run_muontrack_crtreco.fcl
> +physics.analyzers.hitdumper.SelectEvents:  [reco]
Here you need the overrides you need for including the CRTs.

2024-06-19 01:52 UTC, bear-is-asleep commented on sbndcode/Commissioning/fcls/hitdumpermodule.fcl
> + hitdumper_data.readTruth: false
Beth must have pulled changes from develop, which include some recent updates to this fcl. See [PR474](https://github.com/SBNSoftware/sbndcode/pull/474), so these changes are not from her.

2024-06-20 07:23 UTC, henrylay97 commented on sbndcode/Commissioning/fcls/hitdumpermodule.fcl
> + hitdumper_data.readTruth: false
No, I understand what the intention is, there was a typo in this line that Beth has now fixed. As well as a missing reversion which she has also fixed :)

2024-06-20 07:24 UTC, henrylay97 commented on sbndcode/Commissioning/fcls/run_muontrack_crtreco.fcl
> +physics.analyzers.hitdumper.KeepCRTTracks:  true
What about SpacePoints?

To be consistent we should set them as default `false` and then put a conversion line to `true` in here.

Btw, these are also the lines you needed in your reco1 type fcl that we discussed offline Beth!

2024-06-20 12:59 UTC, henrylay97 approved these changes
This is now good to go! @bear-is-asleep 

One final tiny suggestion which you should be able to just click "commit suggestion" for @bethmccusker

2024-06-20 12:59 UTC, henrylay97 commented on sbndcode/Commissioning/fcls/run_muontrack_crtreco.fcl
> +physics.analyzers.hitdumper.KeepCRTTracks:  true
Final comment here... You did it for the reco1 file but not this one!
```suggestion
physics.analyzers.hitdumper.KeepCRTStripHits:  true
physics.analyzers.hitdumper.KeepCRTTracks:  true
physics.analyzers.hitdumper.KeepCRTSpacePoints: true
```

2024-06-20 16:20 UTC, bear-is-asleep requested changes
Hi @bethmccusker and @henrylay97 , this is great and I appreciate both of your hard work to get this done! I do have a few fcl change requests, though. Namely, it'll ensure the defaults are preserved and changes to the muon track fcl will be propagated to your crtreco fcl.

2024-06-20 16:20 UTC, bear-is-asleep commented on sbndcode/Commissioning/fcls/hitdumpermodule.fcl
> +    readMuonHits:             true
I still don't think we should change unrelated hitdumper configuration parameters.

2024-06-20 16:20 UTC, bear-is-asleep commented on sbndcode/Commissioning/fcls/hitdumpermodule.fcl
> + hitdumper_data.readTruth: false
This is from another PR so it's fine

2024-06-20 16:20 UTC, bear-is-asleep commented on sbndcode/Commissioning/fcls/run_muontrack_crtreco.fcl
Would it be possible to use `#include "run_muontrack.fcl"`, this way you don't have to rewrite the entire fcl?

2024-06-20 16:20 UTC, bear-is-asleep commented on sbndcode/Commissioning/fcls/run_muontrack_crtreco.fcl
This would also allow any muon track changes to be propagated to this fcl without changing both.

2024-06-21 07:17 UTC, henrylay97 reviewed
Whilst I agree in principle @bear-is-asleep to some of your comments I'd like to point out the following things:

- The current fcls here are quite messy anyway, the naming doesn't make much sense and neither do the defaults.
- For example, PDS seems to arbitrarily run as default whilst TPC and CRT not?
- None of them really reflect a realistic workflow going forward.

And suggest the following path:
- Beth's PR is merged as is.
- In the "data PR" that I've promised you early next week I will include a tidying up of the fcls in this folder, which you can then review and improve upon in that PR?

2024-06-25 19:58 UTC, bear-is-asleep commented
> Whilst I agree in principle @bear-is-asleep to some of your comments I'd like to point out the following things:
> 
> * The current fcls here are quite messy anyway, the naming doesn't make much sense and neither do the defaults.
> * For example, PDS seems to arbitrarily run as default whilst TPC and CRT not?
> * None of them really reflect a realistic workflow going forward.
> 
> And suggest the following path:
> 
> * Beth's PR is merged as is.
> * In the "data PR" that I've promised you early next week I will include a tidying up of the fcls in this folder, which you can then review and improve upon in that PR?

Hi Henry, sorry for the late response. I don't think I commented on the naming conventions but they seem fine to me (you didn't change the names of anything I don't see). I get hitdumper will be rapidly changing, but we should nonetheless not merge arbitrary changes just because "it's messy anyways". I agree the defaults don't make sense, but if a future contributor sees they were changed in a release, it may be confusing.  Since we're taking commissioning data, it'd be great to update the defaults to things we have data for and work, namely the PDS reco and now CRT track reco. However, I don't expect you or Beth to make these changes, I can probably make these changes myself. 

That being said, I'm happy to approve these changes and I understand your perspective, I don't want to labor you two over a few arbitrary fcl changes! I'm just happy the CRT reco is in. Just saying we need to treat our code with love.

2024-06-25 19:59 UTC, bear-is-asleep requested changes
Awaiting on @henrylay97 to make some fcl changes. When he gives me the go-ahead I'll approve and test the CI.

2024-08-07 20:42 UTC, bear-is-asleep commented on sbndcode/Commissioning/fcls/reco1_sce_comm_muontrack_crtreco.fcl
> +#include "reco1_sce_comm.fcl"
this will now need to be updated to use `"reco1_comm.fcl"`

2024-08-16 17:54 UTC, bear-is-asleep commented
Is this PR still being worked on?

2024-09-06 14:22 UTC, henrylay97 commented
Okay I've provided some tidy up of this to avoid changing default parameters etc.

@bethmccusker can you check that you're happy that the two run fcls that you created still run happily on your files and give you everything you need?

2024-09-13 16:53 UTC, bear-is-asleep commented
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_91_02

2024-09-13 17:06 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for e26:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/23681&builds=)

2024-09-13 17:09 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/23682&builds=)

2024-09-13 17:16 UTC, FNALbuild commented
:x: CI build for SBND Failed at phase build SBND on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/14969&builds=)

:rotating_light: For more details about the failed phase, check the [build SBND phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/14969&platform=Linux%20slf7&phase=build&buildtype=slf7%20c14:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/23682&builds=)

2024-09-13 17:26 UTC, FNALbuild commented
:warning: CI build for SBND Warning at phase ci_tests SBND on slf7 for e26:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/14968&builds=)

:rotating_light: For more details about the warning phase, check the [ci_tests SBND phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/14968&platform=Linux%20slf7&phase=ci_tests&buildtype=slf7%20e26:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/23681&builds=)

2024-09-13 17:28 UTC, merged