Refactor reco2 workflow, and promote standard_reco2_sbnd.fcl back to the main workflow again
SBNSoftware/sbndcode pull request #528
Opened 2024-10-04 16:33 UTC by absolution1

## Description 
This PR refactors reco2, reusing the fcl organisation defined in PR: https://github.com/SBNSoftware/sbndcode/pull/460
This PR
 - Cleans up the reco2 fcls
 - Promotes `standard_reco2_sbnd.fcl` back to the main workflow
 - Removes `reco2_sce.fcl` entirely and updates any dependencies to point to `standard_reco2_sbnd.fcl`

The original and reorganised fcls have been diff'd to check nothing has substantially changed.  There is a minor change in the number of dropped products (more are dropped now).  These are earlier stage products already dropped by reco1, so this is a benign change.  All other diffs are fcl-bookkeeping that should not affect the output (e.g. sequence names changing from `reco2_sce` to `reco2`. I have attached the diffs, for completeness.

I've picked an assortment of reviewers, I'm not anticipating/expecting everyone actually looks.

## Checklist
- [x] Added at least 1 label from [available labels](https://github.com/SBNSoftware/sbndcode/issues/labels?sort=name-asc).
- [x] Assigned at least 1 reviewer under `Reviewers`,
- [x] Assigned all contributers including yourself under `Assignees`
- [ ] Linked any relevant issues under `Developement`
- [ ] Does this PR affect CAF data format? If so, please assign a CAF maintainer ([PetrilloAtWork](https://github.com/PetrilloAtWork) or [JosiePaton](https://github.com/JosiePaton)) as additional reviewer.
- [x] Does this affect the standard workflow? 

[reco2_data_diff.txt](https://github.com/user-attachments/files/17261508/reco2_data_diff.txt)
[reco2_diff.txt](https://github.com/user-attachments/files/17261509/reco2_diff.txt)

2024-10-04 20:57 UTC, marcodeltutto approved these changes
Looks great, thanks @absolution1!

One thing we should probably pay attention to is to make sure that all our fcls end with `_sbnd.fcl` to make sure there's no conflict if there's a similar fcl in `sbncode` or even `icaruscode` in case people set up `icaruscode` in parallel.

2024-10-07 08:22 UTC, henrylay97 approved these changes
Looks good to me! Thank you so much for doing this work @absolution1!

2024-10-07 08:22 UTC, henrylay97 commented on sbndcode/JobConfigurations/standard/reco/config/workflow_reco2.fcl
> +]
I'm just going to mention here that we've often talked about moving a lot of the producers currently run in the CAF stage into reco2 (CRUMBS, stubs, the MCS tool, the PID BDTs etc).

This shouldn't be part of this PR as this is meant to reorganise whilst maintaining behaviour. But now that this workflow fcl is nice & clean, we should look at doing this soon.

2024-10-07 08:22 UTC, henrylay97 commented on sbndcode/JobConfigurations/standard/standard_reco2_sbnd.fcl
> +    ParticleInventoryService:  @local::sbnd_particleinventoryservice
And the longer term plan would be to move these into a table?

2024-10-07 16:08 UTC, bear-is-asleep requested changes
Looks good, we all appreciate your hard work doing this! My only comment was to follow the naming convention in the commissioning folder established by the previous reco1 refactor PR.

2024-10-07 16:08 UTC, bear-is-asleep commented on sbndcode/Commissioning/fcls/reco2_sce_comm.fcl
As with the reco1 changes, the name should be `reco2_comm.fcl`

2024-10-08 14:29 UTC, lynnt20 commented on sbndcode/JobConfigurations/README.md
> +`standard_reco2_sbnd.fcl` has been promoted back to an up-to-date fcl and has rejoined the standard workflow
Might be good to explicitly mention that sce is now included in `standard_reco2_sbnd.fcl` for completion/documentation sake here!

2024-10-08 14:30 UTC, lynnt20 commented on sbndcode/JobConfigurations/standard/standard_reco2_sbnd.fcl
> +#FIXME permanently enable SCE in a service rather than override specific params in this way...
maybe we can delete this `#FIXME` line now since it looks like enabling SCE is through a service?

2024-10-08 14:31 UTC, lynnt20 approved these changes
thank you @absolution1!! this looks great 😄 just left some very minor comments!

2024-10-08 15:15 UTC, henrylay97 commented on sbndcode/JobConfigurations/standard/standard_reco2_sbnd.fcl
> +#FIXME permanently enable SCE in a service rather than override specific params in this way...
I think Dom just means make it the default right? Rather than overrides at the bottom?

2024-10-30 13:09 UTC, absolution1 commented on sbndcode/JobConfigurations/standard/reco/config/workflow_reco2.fcl
> +]
Fully agreed (on including these in reco2, but also not making it part of this PR

2024-10-30 13:09 UTC, absolution1 commented
> Looks great, thanks @absolution1!
> 
> One thing we should probably pay attention to is to make sure that all our fcls end with `_sbnd.fcl` to make sure there's no conflict if there's a similar fcl in `sbncode` or even `icaruscode` in case people set up `icaruscode` in parallel.

Totally agree with this Marco.  
The refactored fcls from reco1 also have this issue, so I might address both reco1 and reco2 in a dedicated PR

2024-10-30 13:10 UTC, absolution1 commented on sbndcode/JobConfigurations/standard/standard_reco2_sbnd.fcl
> +#FIXME permanently enable SCE in a service rather than override specific params in this way...
Hi @lynnt20 
What I meant here is that the upstream service should be default-configured to enable SCE, and then we can remove the includes from the bottom of the fcls

2024-10-30 13:14 UTC, absolution1 commented on sbndcode/JobConfigurations/README.md
> +`standard_reco2_sbnd.fcl` has been promoted back to an up-to-date fcl and has rejoined the standard workflow
Done!
Thanks for noticing that @lynnt20

2024-10-30 13:31 UTC, absolution1 commented on sbndcode/Commissioning/fcls/reco2_sce_comm.fcl
Done.  Thanks @bear-is-asleep

2024-10-30 15:37 UTC, bear-is-asleep commented
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_93_01 SBNSoftware/sbnanaobj@bug/coackley_ciCafv09_91_02

2024-10-30 15:48 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/24083&builds=)

2024-10-30 15:50 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for e26:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/24082&builds=)

2024-10-30 16:27 UTC, FNALbuild commented
:warning: CI build for SBND Warning at phase ci_tests SBND on slf7 for e26:prof - ignored failure for unit_test - ignored warnings for build -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/15283&builds=)

:rotating_light: For more details about the warning phase, check the [ci_tests SBND phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/15283&platform=Linux%20slf7&phase=ci_tests&buildtype=slf7%20e26:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/24082&builds=)

2024-10-30 16:40 UTC, bear-is-asleep commented
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_93_01 SBNSoftware/sbnanaobj@bug/coackley_ciCafv09_91_02

2024-10-30 17:05 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for e26:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/24099&builds=)

2024-10-30 17:06 UTC, FNALbuild commented
:x: CI build for SBND Failed at phase build SBND on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/15300&builds=)

:rotating_light: For more details about the failed phase, check the [build SBND phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/15300&platform=Linux%20slf7&phase=build&buildtype=slf7%20c14:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/24100&builds=)

2024-10-30 17:16 UTC, bear-is-asleep approved these changes

2024-10-30 17:30 UTC, FNALbuild commented
:warning: CI build for SBND Warning at phase ci_tests SBND on slf7 for e26:prof - ignored warnings for build -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/15301&builds=)

:rotating_light: For more details about the warning phase, check the [ci_tests SBND phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/15301&platform=Linux%20slf7&phase=ci_tests&buildtype=slf7%20e26:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/24099&builds=)

2024-10-30 20:01 UTC, bear-is-asleep commented
Ready for merge

2024-10-31 15:30 UTC, merged