Getting CRT out of the MC calib ntuple for now (geometry conflict fix
SBNSoftware/sbndcode pull request #544
Opened 2024-10-23 14:50 UTC by linyan-w

for 24B production)

## Description 
Please provide a detailed description of the changes this pull request introduces. 

## Checklist
- [ ] Added at least 1 label from [available labels](https://github.com/SBNSoftware/sbndcode/issues/labels?sort=name-asc).
- [ ] Assigned at least 1 reviewer under `Reviewers`,
- [ ] Assigned all contributers including yourself under `Assignees`
- [ ] Linked any relevant issues under `Developement`
- [ ] Does this PR affect CAF data format? If so, please assign a CAF maintainer ([PetrilloAtWork](https://github.com/PetrilloAtWork) or [JosiePaton](https://github.com/JosiePaton)) as additional reviewer.
- [ ] Does this affect the standard workflow? 

### Relevant PR links (optional)
Does this PR require merging another PR in a different repository (such as sbnanobj/sbnobj etc.)?

### Link(s) to docdb describing changes (optional)
Is there a docdb describing the issue this solves or the feature added?

2024-10-23 14:54 UTC, linyan-w commented
Somehow the CRT tree in calib ntuple is conflicting with the following error message. Getting rid of the tree temporarily fixes it. This is for the 24B production. We will eventually move the CRT tree back to the calib ntuple.

`%MSG-s ArtException:  PostEndJob 22-Oct-2024 17:55:51 UTC ModuleEndJob
---- EventProcessorFailure BEGIN
  EventProcessor: an exception occurred during current event processing
  ---- EventProcessorFailure BEGIN
    EndPathExecutor: an exception occurred during current event processing
    ---- ScheduleExecutionFailure BEGIN
      Path: ProcessingStopped.
      ---- StdException BEGIN
        An exception was thrown while processing module CRTCalibAna/crtskim run: 257 subRun: 18 event: 1
        std::exception
      ---- StdException END
      Exception going through path end_path
    ---- ScheduleExecutionFailure END
  ---- EventProcessorFailure END
---- EventProcessorFailure END
---- FatalRootError BEGIN
  Fatal Root Error: TTree::SetEntries
  Tree branches have different numbers of entries, eg EventAuxiliary has 0 entries while sim::AuxDetSimChannels_genericcrt__G4. has 9 entries.
  ROOT severity: 2000
---- FatalRootError END
%MSG
Art has completed and will exit with status 1.`

2024-10-24 10:22 UTC, henrylay97 commented
Hi @linyan-w could you provide the path to the file you ran over to produce this segfault please?

2024-10-24 13:52 UTC, linyan-w commented
> Hi @linyan-w could you provide the path to the file you ran over to produce this segfault please?

This is the reco1 path provided by @Mateus F. Carneiro
`/pnfs/sbn/data_add/sbn_nd/poms_production//official/test_MCP2024B/v09_91_02_02/prodoverlay_corsika_cosmics_proton_genie_rockbox_sbnd/gen_g4_detsim_reco1/`

2024-10-28 10:43 UTC, henrylay97 commented
@linyan-w @mattfcs 

I cannot see any artroot files in this directory or it's sub-directories?

2024-10-28 20:31 UTC, linyan-w commented
- PR updated to incorporate the fix, and thus keeping the CRT tree within the calib ntuple.
- The reco2 fcl to process no SCE samples is changed from `standard_reco2_sbnd.fcl` to `standard/detvar_downstream/nosce_reco2_sbnd.fcl`.

2024-10-29 09:46 UTC, henrylay97 requested changes
Thanks @linyan-w 

I've added one request - for keeping the number of unnecessary fcls lower. I've also added a caution for you & @bear-is-asleep on how this PR will interact with other open PRs.

2024-10-29 09:46 UTC, henrylay97 commented on sbndcode/Calibration/CRT/crtskim_sbnd.fcl
> +}
Approve of this method, thanks!

2024-10-29 09:46 UTC, henrylay97 commented on sbndcode/JobConfigurations/standard/detvar_downstream/nosce_reco2_sbnd.fcl
> +physics.end_paths: [stream1, caloskimana_nosce]
This change can be made in `standard_reco2_sbnd.fcl` rather than in a separate fcl.

It is worth pointing out that @absolution1 has a PR open (#528) which will make `standard_reco2_sbnd.fcl` into the "SCE fcl" and make a separate "non-SCE reco2" fcl as well. The order of merging these PRs will matter - and the resulting conflicts should be carefully handled to ensure the behavior is as requested.

2024-10-29 12:55 UTC, linyan-w commented on sbndcode/JobConfigurations/standard/detvar_downstream/nosce_reco2_sbnd.fcl
> +physics.end_paths: [stream1, caloskimana_nosce]
Thanks Henry! What's the approach to move forward? It seems to me Dom's PR will not solve the CRT issue (not separate CRT sce from CRT no sce, so will still crash on no sce sample requesting CRT in the calib ntuple). Tagging @bear-is-asleep

2024-10-29 13:00 UTC, henrylay97 commented on sbndcode/JobConfigurations/standard/detvar_downstream/nosce_reco2_sbnd.fcl
> +physics.end_paths: [stream1, caloskimana_nosce]
I think there needs to be two conversations:
- One regards production. If the plan is to produce a patched tag based on the previous tag then we will need a separate PR that applies this change to the fcls as they were in the previous tag.
- The second regards this PR which solves the problem long term in develop. My recommendation would be to keep this one open until Dom's PR is merged and then ensure this is consistent at that point.

2024-10-30 15:39 UTC, bear-is-asleep commented
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_93_01 SBNSoftware/sbnanaobj@bug/coackley_ciCafv09_91_02

2024-10-30 16:31 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for e26:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/24096&builds=)

2024-10-30 16:32 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/24097&builds=)

2024-10-30 16:54 UTC, FNALbuild commented
:x: CI build for SBND Failed at phase build SBND on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/15297&builds=)

:rotating_light: For more details about the failed phase, check the [build SBND phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/15297&platform=Linux%20slf7&phase=build&buildtype=slf7%20c14:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/24097&builds=)

2024-10-30 16:59 UTC, FNALbuild commented
:warning: CI build for SBND Warning at phase ci_tests SBND on slf7 for e26:prof - ignored warnings for build -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/15296&builds=)

:rotating_light: For more details about the warning phase, check the [ci_tests SBND phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/15296&platform=Linux%20slf7&phase=ci_tests&buildtype=slf7%20e26:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/24096&builds=)

2024-11-01 14:52 UTC, henrylay97 commented
Hi @bear-is-asleep @linyan-w I have now updated this PR such that it is compatible with Dom's PR.

In the process I have:
- Created the `reco2_no_sce_sbnd.fcl` in the right directory. This is the fcl for the calibration workflow that Linyan wanted.
- Updated the `workflow_reco2.fcl` to further group the sequences (making this no SCE fcl easier to make).
- Removed the old `reco_sbnd.fcl` as it is now surplus to requirements (been replaced in function by the `workflow_reco*` fcls)
- Pointed the combined reco1reco2 fcl at the relevant workflow fcls.

@linyan-w I have tested that this new fcl runs on the example file you gave me. You / the calibration group should still check it has what you want in it - I've just tested it runs.

@absolution1 given the expanded scope of this PR could you check my updates to the workflow fcl? I did do a fhicl-dump check before and after on `standard_reco2_sbnd.fcl` and the only change is swapping the order of `opt0finder` & `caloskimCalorimetry` in the producers sequence.

2024-11-04 14:09 UTC, linyan-w commented
Looks great to me!

2024-11-04 16:24 UTC, bear-is-asleep approved these changes
Approving on behalf on previous comments

2024-11-04 16:24 UTC, bear-is-asleep commented
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_93_01 SBNSoftware/sbnanaobj@bug/coackley_ciCafv09_91_02

2024-11-04 16:36 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/24143&builds=)

2024-11-04 16:45 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for e26:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/24142&builds=)

2024-11-04 17:10 UTC, FNALbuild commented
:x: CI build for SBND Failed at phase ci_tests SBND on slf7 for e26:prof - ignored failure for unit_test - ignored warnings for build -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/15342&builds=)

:rotating_light: For more details about the failed phase, check the [ci_tests SBND phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/15342&platform=Linux%20slf7&phase=ci_tests&buildtype=slf7%20e26:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/24142&builds=)

2024-11-07 10:19 UTC, henrylay97 commented
trigger build LArSoft/lar*@LARSOFT_SUITE_v09_93_01 SBNSoftware/sbnanaobj@bug/coackley_ciCafv09_91_02

2024-11-07 10:31 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/24167&builds=)

2024-11-07 10:32 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for e26:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/24166&builds=)

2024-11-07 10:51 UTC, FNALbuild commented
:x: CI build for SBND Failed at phase build SBND on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/15362&builds=)

:rotating_light: For more details about the failed phase, check the [build SBND phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/15362&platform=Linux%20slf7&phase=build&buildtype=slf7%20c14:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/24167&builds=)

2025-01-16 11:01 UTC, RachelCoackley commented
trigger build RachelCoackley/larreco>larreco@v09_93_01rachel LArSoft/lar*@LARSOFT_SUITE_v09_93_01 SBNSoftware/sbncode@v09_93_01_p02 SBNSoftware/sbnanaobj@bug/coackley_ciCafv09_91_02 SBNSoftware/sbndaq-artdaq-core@v1_10_03 SBNSoftware/sbnobj@v09_19_05

2025-01-16 11:36 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/24642&builds=)

2025-01-16 11:46 UTC, FNALbuild commented
:x: CI build for SBND Failed at phase build SBND on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/15764&builds=)

:rotating_light: For more details about the failed phase, check the [build SBND phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/15764&platform=Linux%20slf7&phase=build&buildtype=slf7%20c14:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/24642&builds=)

2025-01-16 11:46 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for e26:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/24641&builds=)

2025-01-16 12:08 UTC, FNALbuild commented
:warning: CI build for SBND Warning at phase ci_tests SBND on slf7 for e26:prof - ignored warnings for build -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/15767&builds=)

:rotating_light: For more details about the warning phase, check the [ci_tests SBND phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/15767&platform=Linux%20slf7&phase=ci_tests&buildtype=slf7%20e26:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/24641&builds=)

2025-01-16 20:52 UTC, bear-is-asleep commented
Looks like the gdml changes got into this PR.

2025-01-16 20:53 UTC, bear-is-asleep commented
Approved, merge CRT gdml first.

2025-01-21 20:50 UTC, closed without merging