Adding reco fcls that keep RawDigit data products
SBNSoftware/sbndcode pull request #558
Opened 2024-11-12 22:22 UTC by hjscott1

## Description 
Introduces `reco1_rawdigit.fcl` and `reco2_rawdigt.fcl` to `sbndcode` into the standard/reco directory. These fcls perform the standard reco1/reco2 workflow, keeping `RawDigit` waveform information and running the SBND `track_caloskimmer` module to produce caloskim ntuples with `wiresX.adcs` branches filled with TPC waveform information. The fcls are currently configured to reconstruct deconvolved SBND data files, but can be used for mc workflows.

## Checklist
- [N/A] Added at least 1 label from [available labels](https://github.com/SBNSoftware/sbndcode/issues/labels?sort=name-asc).
  It won't let me add the labels for some reason, but the labels should be 'data', 'reco1/reco2' and 'tpc'
- [Yes] Assigned at least 1 reviewer under `Reviewers`,
- [Yes] Assigned all contributers including yourself under `Assignees`
- [N/A] Linked any relevant issues under `Developement`
- [No] Does this PR affect CAF data format? If so, please assign a CAF maintainer ([PetrilloAtWork](https://github.com/PetrilloAtWork) or [JosiePaton](https://github.com/JosiePaton)) as additional reviewer.
- [No] Does this affect the standard workflow? 

### Relevant PR links (optional)
Does this PR require merging another PR in a different repository (such as sbnanobj/sbnobj etc.)?
No

### Link(s) to docdb describing changes (optional)
Is there a docdb describing the issue this solves or the feature added?
No

2024-11-13 10:21 UTC, absolution1 requested changes
Hi @hjscott1 
Thank you for submitting this PR.  The changes look like they work, but it would be good to put the list of drops in the dedicated fcl and pass the entire sequence to reco1_data.fcl or reco2_data.fcl

2024-11-13 10:21 UTC, absolution1 commented on sbndcode/JobConfigurations/standard/reco/reco1_rawdigit.fcl
> +        	]
Could you define this block in `reco1_drops.fcl` (https://github.com/SBNSoftware/sbndcode/blob/develop/sbndcode/JobConfigurations/standard/reco/config/drops_reco1.fcl) and then pass it as a sequence here?

2024-11-13 10:21 UTC, absolution1 commented on sbndcode/JobConfigurations/standard/reco/reco2_rawdigit.fcl
> +outputs.out1.outputCommands: [
same comment as above, but you could probably pass the same sequence as used in reco1

2024-11-14 22:10 UTC, linyan-w approved these changes
Looks good to me. Thanks Harry (and Dom)!

2025-01-15 16:51 UTC, RachelCoackley commented
@hjscott1 please would you be able to resolve the conflicts? Thanks!! :)

2025-01-17 10:59 UTC, RachelCoackley commented
trigger build RachelCoackley/larreco>larreco@v09_93_01rachel LArSoft/lar*@LARSOFT_SUITE_v09_93_01 SBNSoftware/sbncode@v09_93_01_p02 SBNSoftware/sbnanaobj@bug/coackley_ciCafv09_91_02 SBNSoftware/sbndaq-artdaq-core@v1_10_03 SBNSoftware/sbnobj@v09_19_05

2025-01-22 21:41 UTC, bear-is-asleep requested changes
Looks alright! Can I recommend you review #603 to make sure the naming convention is the same? These changes will overlap. Can you change the name to `reco1_data_rawdigit.fcl`, so it sticks with the suffix of the fcl it inherits from (same for the reco2 fcl).

2025-01-23 17:20 UTC, bear-is-asleep approved these changes

2025-01-23 17:20 UTC, bear-is-asleep commented
trigger build RachelCoackley/larreco>larreco@v09_93_01rachel LArSoft/lar*@LARSOFT_SUITE_v09_93_01 SBNSoftware/sbncode@v09_93_01_p02 SBNSoftware/sbnanaobj@bug/coackley_ciCafv09_91_02 SBNSoftware/sbndaq-artdaq-core@v1_10_03 SBNSoftware/sbnobj@v09_19_05

2025-01-23 17:33 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for e26:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/24700&builds=)

2025-01-23 17:37 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/24701&builds=)

2025-01-23 17:47 UTC, FNALbuild commented
:x: CI build for SBND Failed at phase build SBND on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/15825&builds=)

:rotating_light: For more details about the failed phase, check the [build SBND phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/15825&platform=Linux%20slf7&phase=build&buildtype=slf7%20c14:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/24701&builds=)

2025-01-23 17:52 UTC, FNALbuild commented
:warning: CI build for SBND Warning at phase ci_tests SBND on slf7 for e26:prof - ignored warnings for build -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/15824&builds=)

:rotating_light: For more details about the warning phase, check the [ci_tests SBND phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/15824&platform=Linux%20slf7&phase=ci_tests&buildtype=slf7%20e26:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/24700&builds=)

2025-01-23 19:48 UTC, bear-is-asleep commented
Approved - Passes CI with unrelated CAF warnings from CNN

2025-01-24 19:02 UTC, merged