Keep CRT tracks in hitdumper by default
SBNSoftware/sbndcode pull request #560
Opened 2024-11-15 17:01 UTC by bear-is-asleep

## Description 
Keep CRT tracks in hitdumper by default.

## Checklist
- [ ] Added at least 1 label from [available labels](https://github.com/SBNSoftware/sbndcode/issues/labels?sort=name-asc).
- [ ] Assigned at least 1 reviewer under `Reviewers`,
- [ ] Assigned all contributers including yourself under `Assignees`
- [ ] Linked any relevant issues under `Developement`
- [ ] Does this PR affect CAF data format? If so, please assign a CAF maintainer ([PetrilloAtWork](https://github.com/PetrilloAtWork) or [JosiePaton](https://github.com/JosiePaton)) as additional reviewer.
- [ ] Does this affect the standard workflow? 

### Relevant PR links (optional)
Does this PR require merging another PR in a different repository (such as sbnanobj/sbnobj etc.)?

### Link(s) to docdb describing changes (optional)
Is there a docdb describing the issue this solves or the feature added?

2024-11-18 09:09 UTC, henrylay97 requested changes
Thanks Bear - I approve of this default behaviour. I've suggested a second default change with the same reasoning.

2024-11-18 09:09 UTC, henrylay97 commented on sbndcode/Commissioning/fcls/hitdumpermodule.fcl
>      KeepCRTSpacePoints:       false
Would also be good to keep the space points - if the tracks are produced the space points have to be so they will also be on the event.

```suggestion
    KeepCRTSpacePoints:       true
```

2024-12-16 15:46 UTC, bear-is-asleep commented
@henrylay97 approved this.

2025-01-15 15:35 UTC, RachelCoackley commented
trigger build RachelCoackley/larreco>larreco@v09_93_01rachel LArSoft/lar*@LARSOFT_SUITE_v09_93_01 SBNSoftware/sbncode@v09_93_01_p01 SBNSoftware/sbndcode@v09_93_01_01 SBNSoftware/sbnanaobj@bug/coackley_ciCafv09_91_02 SBNSoftware/sbndaq-artdaq-core@v1_10_02 SBNSoftware/sbnobj@v09_19_05

2025-01-15 16:03 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/24612&builds=)

2025-01-15 16:23 UTC, FNALbuild commented
:x: CI build for SBND Failed at phase build SBND on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/15734&builds=)

:rotating_light: For more details about the failed phase, check the [build SBND phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/15734&platform=Linux%20slf7&phase=build&buildtype=slf7%20c14:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/24612&builds=)

2025-01-15 16:49 UTC, RachelCoackley commented
@bear-is-asleep please would you be able to resolve the conflicts? Thanks!! :)

2025-01-15 16:50 UTC, FNALbuild commented
:x: CI build for SBND Failed at phase ci_tests SBND on slf7 for e26:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/15735&builds=)

:rotating_light: For more details about the failed phase, check the [ci_tests SBND phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/15735&platform=Linux%20slf7&phase=ci_tests&buildtype=slf7%20e26:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/24611&builds=)

2025-01-23 17:21 UTC, closed without merging