Update reco1 to use channel status service
SBNSoftware/sbndcode pull request #566
Opened 2024-12-06 16:12 UTC by bear-is-asleep

## Description 
Allows Cluster3D to find bad channels through the channel status service.

## Checklist
- [ ] Added at least 1 label from [available labels](https://github.com/SBNSoftware/sbndcode/issues/labels?sort=name-asc).
- [ ] Assigned at least 1 reviewer under `Reviewers`,
- [ ] Assigned all contributers including yourself under `Assignees`
- [ ] Linked any relevant issues under `Developement`
- [ ] Does this PR affect CAF data format? If so, please assign a CAF maintainer ([PetrilloAtWork](https://github.com/PetrilloAtWork) or [JosiePaton](https://github.com/JosiePaton)) as additional reviewer.
- [ ] Does this affect the standard workflow? 

### Relevant PR links (optional)
[sbncode PR 490](https://github.com/SBNSoftware/sbncode/pull/490)

### Link(s) to docdb describing changes (optional)
Is there a docdb describing the issue this solves or the feature added?

2024-12-09 14:22 UTC, absolution1 requested changes
Hi @bear-is-asleep 
Thanks for making this change, its been on my list for a bit.

I think we should avoid manually override the ChannelStatusService in the job fcl when the service is already defined in the upstream service block definition.

Could you move loading in the data service to here: https://github.com/SBNSoftware/sbndcode/blob/develop/sbndcode/LArSoftConfigurations/services_sbnd.fcl#L88

Slightly longer term we should scrub the data channel service completely, and have a single service.
For now, I think this PR is a good fix however.

2024-12-16 16:50 UTC, bear-is-asleep commented
> Hi @bear-is-asleep Thanks for making this change, its been on my list for a bit.
> 
> I think we should avoid manually override the ChannelStatusService in the job fcl when the service is already defined in the upstream service block definition.
> 
> Could you move loading in the data service to here: https://github.com/SBNSoftware/sbndcode/blob/develop/sbndcode/LArSoftConfigurations/services_sbnd.fcl#L88
> 
> Slightly longer term we should scrub the data channel service completely, and have a single service. For now, I think this PR is a good fix however.

Done! Wanna give it another check?

2025-01-09 16:52 UTC, absolution1 approved these changes
Thank you!

2025-01-15 16:35 UTC, RachelCoackley commented
trigger build RachelCoackley/larreco>larreco@v09_93_01rachel LArSoft/lar*@LARSOFT_SUITE_v09_93_01 SBNSoftware/sbncode@v09_93_01_p01 SBNSoftware/sbndcode@v09_93_01_01 SBNSoftware/sbnanaobj@bug/coackley_ciCafv09_91_02 SBNSoftware/sbndaq-artdaq-core@v1_10_02 SBNSoftware/sbnobj@v09_19_05

2025-01-15 16:47 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/24618&builds=)

2025-01-15 16:54 UTC, FNALbuild commented
:x: CI build for SBND Failed at phase build SBND on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/15739&builds=)

:rotating_light: For more details about the failed phase, check the [build SBND phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/15739&platform=Linux%20slf7&phase=build&buildtype=slf7%20c14:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/24618&builds=)

2025-01-15 16:57 UTC, FNALbuild commented
:x: CI build for SBND Failed at phase build SBND on slf7 for e26:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/15740&builds=)

:rotating_light: For more details about the failed phase, check the [build SBND phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/15740&platform=Linux%20slf7&phase=build&buildtype=slf7%20e26:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/24617&builds=)

2025-01-16 11:07 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for e26:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/24629&builds=)

2025-01-16 11:10 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/24630&builds=)

2025-01-16 11:20 UTC, FNALbuild commented
:x: CI build for SBND Failed at phase build SBND on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/15755&builds=)

:rotating_light: For more details about the failed phase, check the [build SBND phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/15755&platform=Linux%20slf7&phase=build&buildtype=slf7%20c14:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/24630&builds=)

2025-01-16 11:29 UTC, FNALbuild commented
:warning: CI build for SBND Warning at phase ci_tests SBND on slf7 for e26:prof - ignored failure for unit_test - ignored warnings for build -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/15753&builds=)

:rotating_light: For more details about the warning phase, check the [ci_tests SBND phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/15753&platform=Linux%20slf7&phase=ci_tests&buildtype=slf7%20e26:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/24629&builds=)

2025-01-16 13:14 UTC, RachelCoackley commented
@bear-is-asleep CI passed but there are a few [ci_test](https://dbweb8.fnal.gov:8443/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/15753&platform=Linux%20slf7&phase=ci_tests&buildtype=slf7%20e26:prof) warnings, please can you confirm these are as expected? Thanks! :) 

(I think the caf warnings are okay)

2025-01-27 21:19 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for e26:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/24773&builds=)

2025-01-27 21:22 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/24774&builds=)

2025-01-27 21:32 UTC, FNALbuild commented
:x: CI build for SBND Failed at phase build SBND on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/15876&builds=)

:rotating_light: For more details about the failed phase, check the [build SBND phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/15876&platform=Linux%20slf7&phase=build&buildtype=slf7%20c14:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/24774&builds=)

2025-01-27 21:38 UTC, FNALbuild commented
:warning: CI build for SBND Warning at phase ci_tests SBND on slf7 for e26:prof - ignored warnings for build -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/15875&builds=)

:rotating_light: For more details about the warning phase, check the [ci_tests SBND phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/15875&platform=Linux%20slf7&phase=ci_tests&buildtype=slf7%20e26:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/24773&builds=)

2025-01-27 22:00 UTC, bear-is-asleep commented
We should wait for the reference update to approve, can you trigger the CI once this is ready @RachelCoackley ?

2025-02-04 19:35 UTC, bear-is-asleep commented
trigger build RachelCoackley/larreco>larreco@v09_93_01rachel LArSoft/lar*@LARSOFT_SUITE_v09_93_01 SBNSoftware/sbncode@bugfix/hlay_mcs_invalid_read SBNSoftware/sbnanaobj@bug/coackley_ciCafv09_91_02 SBNSoftware/sbndaq-artdaq-core@v1_10_03 SBNSoftware/sbnobj@v09_19_05 SBNSoftware/sbndutil@v09_93_01_02

2025-02-04 19:48 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for e26:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/24896&builds=)

2025-02-04 19:51 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/24897&builds=)

2025-02-04 20:00 UTC, FNALbuild commented
:x: CI build for SBND Failed at phase build SBND on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/15955&builds=)

:rotating_light: For more details about the failed phase, check the [build SBND phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/15955&platform=Linux%20slf7&phase=build&buildtype=slf7%20c14:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/24897&builds=)

2025-02-04 20:13 UTC, FNALbuild commented
:warning: CI build for SBND Warning at phase ci_tests SBND on slf7 for e26:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/15953&builds=)

:rotating_light: For more details about the warning phase, check the [ci_tests SBND phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/15953&platform=Linux%20slf7&phase=ci_tests&buildtype=slf7%20e26:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/24896&builds=)

2025-02-04 20:16 UTC, bear-is-asleep commented
trigger build RachelCoackley/larreco>larreco@v09_93_01rachel LArSoft/lar*@LARSOFT_SUITE_v09_93_01 SBNSoftware/sbncode@bugfix/hlay_mcs_invalid_read SBNSoftware/sbnanaobj@bug/coackley_ciCafv09_91_02 SBNSoftware/sbndaq-artdaq-core@v1_10_03 SBNSoftware/sbnobj@v09_19_05 SBNSoftware/sbndutil@v09_93_01_02

2025-02-04 20:29 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for e26:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/24900&builds=)

2025-02-04 20:32 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/24901&builds=)

2025-02-05 00:12 UTC, bear-is-asleep commented
trigger build RachelCoackley/larreco>larreco@v09_93_01rachel LArSoft/lar*@LARSOFT_SUITE_v09_93_01 SBNSoftware/sbncode@bugfix/hlay_mcs_invalid_read SBNSoftware/sbnanaobj@bug/coackley_ciCafv09_91_02 SBNSoftware/sbndaq-artdaq-core@v1_10_03 SBNSoftware/sbnobj@v09_19_05 SBNSoftware/sbndutil@v09_93_01_02

2025-02-05 00:25 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for e26:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/24906&builds=)

2025-02-05 00:28 UTC, FNALbuild commented
:heavy_check_mark: CI build for LArSoft Succeeded on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app//view_builds/index?offset=0&builds=lar_ci/24907&builds=)

2025-02-05 00:41 UTC, FNALbuild commented
:x: CI build for SBND Failed at phase build SBND on slf7 for c14:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/15961&builds=)

:rotating_light: For more details about the failed phase, check the [build SBND phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/15961&platform=Linux%20slf7&phase=build&buildtype=slf7%20c14:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/24907&builds=)

2025-02-05 00:49 UTC, FNALbuild commented
:warning: CI build for SBND Warning at phase ci_tests SBND on slf7 for e26:prof -- details available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/view_builds/index?offset=0&builds=sbnd_ci/15960&builds=)

:rotating_light: For more details about the warning phase, check the [ci_tests SBND phase logs](https://dbweb0.fnal.gov/LarCI/app/ns:SBND/build_detail/phase_details?build_id=sbnd_ci/15960&platform=Linux%20slf7&phase=ci_tests&buildtype=slf7%20e26:prof)

parent CI build details are available through the [CI dashboard](https://dbweb0.fnal.gov/LarCI/app/view_builds/index?offset=0&builds=lar_ci/24906&builds=)

2025-02-05 01:33 UTC, bear-is-asleep commented
Approved, changes the channel service.

2025-02-05 01:35 UTC, merged