Feature/maxd ptb decoder update
SBNSoftware/sbndcode pull request #581
Opened 2024-12-17 03:00 UTC by maxdubnowski

## Description 
Description added to the document included

## Checklist
- [ ] Added at least 1 label from [available labels](https://github.com/SBNSoftware/sbndcode/issues/labels?sort=name-asc).
- [ ] Assigned at least 1 reviewer under `Reviewers`,
- [ ] Assigned all contributers including yourself under `Assignees`
- [ ] Linked any relevant issues under `Developement`
- [ ] Does this PR affect CAF data format? If so, please assign a CAF maintainer ([PetrilloAtWork](https://github.com/PetrilloAtWork) or [JosiePaton](https://github.com/JosiePaton)) as additional reviewer.
- [ ] Does this affect the standard workflow? 

[PTB Decoder Update (1).pdf](https://github.com/user-attachments/files/18159471/PTB.Decoder.Update.1.pdf)

2024-12-17 16:40 UTC, henrylay97 requested changes
Hi @maxdubnowski  really sorry for the drive-by unsolicited review. This looks like a **lot** of really good work.

@lynnt20 and I were making use of this PR to incorporate some decoded PTB information into the CRT/PMT workflows and in the process I noticed a few minor things I'd recommend changing.

Note - this doesn't constitute a review of the more technical PTB/Exposure Accounting changes. These will still need reviewing by Lauren :D

2024-12-17 16:40 UTC, henrylay97 commented on sbndcode/Decoders/PTB/SBNDPTBDecoder_module.cc
> +   std::cout << "Run: " << _run  << "  SubRun: " << _subrun  << "  Event: " << _event  << std::endl;
Should avoid adding unguarded print statement to a module run in production jobs.

Would recommend either removing or hiding behind a debug flag.

2024-12-17 16:40 UTC, henrylay97 commented on sbndcode/Decoders/PTBAna/CMakeLists.txt
> +
Remove whitespace?

2024-12-17 16:40 UTC, henrylay97 commented on sbndcode/Decoders/PTB/SBNDPTBDecoder_module.cc
> +
Maybe this could be kept but hidden behind a debug flag if you add one?

2024-12-17 16:40 UTC, henrylay97 commented on sbndcode/Decoders/PTBAna/anaPrint_EVB1_art4_run14728all.root
Remove accidental commit of binary files

2024-12-17 16:40 UTC, henrylay97 commented on sbndcode/Decoders/PTBAna/output.root
Remove accidental commit of binary files

2024-12-17 16:40 UTC, henrylay97 commented on sbndcode/Decoders/PTBAna/run_ptbana.fcl
> +//#include "crtbacktrackeralg_sbnd.fcl"
Remove all the commented lines :D

2024-12-17 16:40 UTC, henrylay97 commented on sbndcode/Decoders/PTBAna/run_ptbana_data.fcl
> +
Likewise - remove commented lines

2024-12-17 16:40 UTC, henrylay97 commented on ups/product_deps
> +sbncode		v10_01_03       -
Remove change to newer sbncode. I appreciate you need the updated objects. You should make clear in the PR description what version of `sbndaq_artdaq_core` you need (is it `v1_10_02`?) and then the release manager will decide how to achieve that in the best way.

2024-12-17 16:58 UTC, henrylay97 commented on sbndcode/Decoders/PTBAna/CMakeLists.txt
> +
Oh also - possibly the PTBAna folder should not be a sub-folder of Decoders - but that's one for @bear-is-asleep to weigh in on

2024-12-17 18:33 UTC, bear-is-asleep commented on sbndcode/Decoders/PTBAna/CMakeLists.txt
> +
Thanks Henry, I agree. The best place may be its own standalone folders as other ana folders are.

2024-12-17 22:10 UTC, maxdubnowski commented on sbndcode/Decoders/PTBAna/CMakeLists.txt
> +
I forgot I had PTBAna in there in the first place!

2024-12-18 08:29 UTC, henrylay97 commented on sbndcode/Decoders/PTB/SBNDPTBDecoder_module.cc
>  int _run; int _subrun; int _event;
Should now remove these unused variables :)

2024-12-18 08:31 UTC, henrylay97 reviewed
Thanks Max - so quick! Couple more tiny tidying comments from my side then over to the actual experts! ;P

2024-12-18 15:11 UTC, jzennamo commented
This looked good to my untrained eyes but I defer to @terezakroupa for a final expert approval

2024-12-18 16:18 UTC, terezakroupa commented on sbndcode/PTBAna/PTBAnalysis_module.cc
> +	  int upBit[10] = {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1};
This places a limit of maximum 10 HLTs set at the same time. Most likely the case most of the time, but could be more generic.

2024-12-18 16:20 UTC, terezakroupa commented on sbndcode/PTBAna/PTBAnalysis_module.cc
> +	  for(int i=0; i<32;i++){
Double use of "i" in the nested loop. I know this has been tested, but using "j" could avoid possible confusion.

2024-12-18 16:29 UTC, terezakroupa approved these changes
This looks great. All my comments (including the above) can very well be addressed in a next upgrade and are not critical for this to go in.

2024-12-18 16:29 UTC, terezakroupa commented on sbndcode/Decoders/PTB/SBNDPTBDecoder_module.cc
> +		tstruct.gate_counter = 0;
Do we want this to be something indicating absence of value a little more? 0 could be an actual gate counter

2024-12-18 16:29 UTC, terezakroupa commented on sbndcode/Decoders/PTB/sbndptb.h
> +      ULong64_t prev_timestamp;
These (and gate_counter for LLTs) will remain unfilled. Is that preferable over filling them with a set value?

2024-12-18 22:06 UTC, merged